### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by Aleksansdr** [ReactiveX/RxSwift#2078] opened 2019-09-27 10:54 UTC
ITMS-90809: Deprecated API Usage — Apple will stop accepting submissions of apps that use UIWebView APIs

**Comment by gringoireDM** [comment] 2019-09-27 11:15
This is a duplicate of https://github.com/ReactiveX/RxSwift/issues/2055

**Comment by Tayphoon** [comment] 2019-10-12 08:52
When this fix will be released?

**Comment by freak4pc** [comment] 2019-10-12 08:53
Please read the discussion on #2055.

**Closed by freak4pc** 2019-10-12 08:53 UTC

**Comment by Tayphoon** [comment] 2019-10-12 08:58
To many words, without solution. I can not point to master.

**Comment by freak4pc** [comment] 2019-10-12 09:01
1. RxSwift is an open-source project, with many contributors working unpaid on it. We do not owe a specific timeline to consumers and yet we do the work we do out of love for it and the community.

2. We provided plenty explanations mentioning this is just a warning from Apple and nothing that is actually critical at this point. We've shipped dozens of apps with RxSwift _and_ this warning with no real issue. 

3. We provided the plan openly, e.g. releasing RxSwift 6 targeting Xcode 11 & Swift 5.1 soon. We have no plan to commit to a specific date exactly due to the fact this is purely a warning and we'd like to add more content into RxSwift 6. There's no reason to pressure this release for something as non-critical as this warning.

4. If all of these don't fit you, feel free to fork the project and do as you wish. It is Open Source, As I mentioned. You can also direct to `master`, as mentioned before.
