### ISSUE TITLE
UserDefaults subscribing issue

### ISSUE THREAD

**Issue by minuscorp** [ReactiveX/RxSwift#927] opened 2016-10-05 20:02 UTC
**Short description of the issue**:

 `NSObject` Reactive category `observe` does not work with `NotificationCenter` because is not KVO complant

**Self contained code example that reproduces the issue**:

```swift
  NotificationCenter.default.rx.observe(String.self, "someKeyPath")
    .subscribe(onNext: { value in print(value ?? "") })
NotificationCenter.default.setString("Hello", forKey: "someKeyPath")
```

**Xcode version**:

```
  Xcode 8.0
```

**Expected outcome**:

  Receiving values of the UserDefaults changing over time. I'd like to know or have some tips (maybe using `UserDefaults.defaultsDidChangeNotification` over `NotificationCenter` reactive extension) about how and if its suitable as a RxCocoa future extension.

**What actually happens**:

  Nothing at all.

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones) 7.3 and 8.0
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by minuscorp** [comment] 2016-10-06 08:50
Here I leave the workaround I use to solve this:

```swift
extension Reactive where Base: UserDefaults {
    
    public func `default`<E: Equatable>(_ type: E.Type, _ keyPath: String) -> Observable<E?> {
        let center = NotificationCenter.default
        let initial = base.object(forKey: keyPath) as? E
        let changes = center.rx.notification(UserDefaults.didChangeNotification)
            .map { _ in
                self.base.object(forKey: keyPath) as? E
        }
        
        return Observable<E?>.just(initial)
            .concat(changes)
            .distinctUntilChanged { previous, next in
                guard let previous = previous, let next = next else {
                    return false
                }
                return previous == next
        }
    }
}
```

**Comment by kzaher** [comment] 2016-10-07 19:25
Hi @minuscorp ,

I don't understand the issue. 

`NSNotificationCenter` is notification mechanism.
`UserDefaults` is another entity separate from notifications.

Are you reporting a bug or requesting `UserDefaults` extension?

I think you can use KVO extensions on `UserDefaults`.

```swift
        let defaults = UserDefaults.standard
        _ = defaults.rx.observe(String.self, "unicorn").subscribe(onNext: { value in
            print(value)
        })

        defaults.set("unicorn popcorn", forKey: "unicorn")
```

**Comment by minuscorp** [comment] 2016-10-07 21:07
Sorry I got the title totally wrong. My issue is with `UserDefaults` observing. My first approach was as you mentioned use `observe` as the documentation of the class tells that is kvo compliant, bit it seems it isn't or it does not work with the` observe` feature.

My approach to make it work was finally using  the `NotificationCenter` to obtain notifications over every change in the defaults (not very efficient) and look for `Equatable` ones to do the mapping and check for different ones.

I'm doing something wrong with the `observe` and `UserDefaults`?

**Comment by kzaher** [comment] 2016-10-09 09:59
Hi @minuscorp ,

I don't know if you were doing something wrong with `UserDefaults` originally because you haven't provided that code. You've provided code sample using KVO on `NotificationCenter`.

In my previous response I've pasted code that works with `UserDefaults` by using KVO extensions that I have tested and it works as far as I can tell.

**Comment by minuscorp** [comment] 2016-10-09 13:24
Sorry, even I got the example bad...

```swift
static let Defaults = UserDefaults.defaults

// Somewhere in my Networking Manager:
Defaults.rx.observe(String.self, kDefaultTokenKey)
.subscribe(onNext: { print("Authentication Token: \($0))"})
.addDisposableTo(disposeBag)

// Somewhere in my LoginViewController:
UserOperations.login(with: credentials)
.do(onNext: { token in Defaults.setString(token, forKey: kDefaultTokenKey) })
.subscribe(onCompleted: { /* end the operation */ })
.addDisposableTo(disposeBag)
 ```

That is definetely not working, _BUT_ I'm receiving _only the first_ value of the `observe`, no updates at all.

**Comment by kzaher** [comment] 2016-10-09 14:37
Hi @minuscorp ,

you have probably lost reference to a dispose bag and it unsubscribed your observers.

```
/**
Thread safe bag that disposes added disposables on `deinit`.
*/
```

You haven't provided a self contained code example, so I can't use it to reproduce the reported issue.

Self contained means that I should be able to just run your code as it is.

I've provided you a self contained code example that as far as I can tell works.

**Comment by minuscorp** [comment] 2016-10-09 15:56
Hello, this is the code I'm using:

```swift

fileprivate lazy var loginAction: CocoaAction = {
        return CocoaAction { _ in
            return UserOperations.login(username: self.emailTextField.text ?? "", password: self.passwordTextField.text ?? "")
                .do(onNext: {
                        token in
                        UserDefaults.standard.setString(token, forKey: kDefaultTokenKey)
                    },
                    onError: {
                        error in
                        let appDelegate = UIApplication.shared.delegate as! AppDelegate
                        appDelegate.window?.rootViewController?.view.makeToast(error.localizedDescription)
                    }
                )
                .map{ _ in () }
        }
    }()
``` 
Which I bind to the tap of the button (I'm using `Action` RxSwift's library for this) and this call is inside an `UIViewController`

On the other hand there is a `AuthenticationManager` which is a singleton initialized once the application is ready:

```swift
UserDefaults.standard.rx.observe(String.self, kDefaultTokenKey)
            .takeUntil(self.rx.deallocating)
            .subscribeOn(MainScheduler.instance)
            .subscribe(onNext: {
                [weak self]
                token in
                guard let `self` = self else { return }
                self.handleTokenBehavior(token)
            })
            .addDisposableTo(disposeBag)
```
This code gets the current value (at application load) of the default but not the subsequent changes made on it.

**Comment by kzaher** [comment] 2016-10-09 20:19
Hi @minuscorp ,

can you please confirm that running this code works for you?

```swift
       let defaults = UserDefaults.standard
        _ = defaults.rx.observe(String.self, "unicorn").subscribe(onNext: { value in
            print(value)
        })

        defaults.set("unicorn popcorn", forKey: "unicorn")
```

**Comment by minuscorp** [comment] 2016-10-10 10:25
It does not work:

```swift
_ = Defaults.rx.observe(String.self, kDefaultTokenKey)
            //.takeUntil(self.rx.deallocating)
            .subscribeOn(MainScheduler.instance)
            .subscribe(onNext: {
                token in
                self.handleTokenBehavior(token)
            })
            //.addDisposableTo(disposeBag)
Defaults[.token] = "hello"
```

**Comment by kzaher** [comment] 2016-10-10 20:52
Hi @minuscorp ,

I've again tried

```swift
import Foundation
import RxCocoa

let kDefaultTokenKey = "DefaultToken"

let defaults = UserDefaults.standard
_ = defaults.rx.observe(String.self, kDefaultTokenKey)
    .subscribeOn(MainScheduler.instance)
    .subscribe(onNext: {
        token in
        print("\(token)")
    })
defaults.set("hello", forKey: kDefaultTokenKey)
```

and it works fine for me.

It is possible that you have something other installed in your environment that interferes with Rx KVO mechanism. 

I would suggest trying it out in a new project. 
* If it works, then you have some other library interfering with Rx in your project
* If it doesn't work on a fresh project, you can zip and send me the project and I can take another look and try to debug this

**Comment by minuscorp** [comment] 2016-10-11 14:12
Hello, today I can't confirm you if it's working or not altough I suppose it should work in a clean project, which makes me wonder why something would break a KVO system...

This is my pod list:
```
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'FBSDKLoginKit'
pod 'Eureka', '2.0.0-beta.1'
pod 'ImageRow', '~> 1.0'
pod 'HCSStarRatingView'
pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'
pod 'IQKeyboardManagerSwift'
pod 'MTMigration'
pod 'MZTimerLabel'
pod 'SDWebImage'
pod 'Fabric'
pod 'Crashlytics'
pod 'DZNEmptyDataSet'
pod 'ReachabilitySwift'
pod 'MRProgress'
pod 'couchbase-lite-ios'
pod 'CocoaLumberjack/Swift'
pod 'PermissionScope'
#pod 'SwiftString', :git => 'https://github.com/iamjono/SwiftString.git'
pod 'PureLayout'
pod 'MarqueeLabel', :git => 'https://github.com/cbpowell/MarqueeLabel.git', :branch => 'swift-3.0'
pod 'Whisper', :git => 'http://github.com/hyperoslo/whisper.git', :branch => 'swift-3'
#pod 'SwiftMessages' 
pod 'PKRevealController', '>= 2.0.6'
pod 'SwiftyUserDefaults'
pod 'SDWebImage'
pod 'Solar'
pod 'Aardvark'
pod 'Toast-Swift', :git => 'https://github.com/scalessec/Toast-Swift.git', :branch => 'master'
pod 'CryptoSwift'
pod 'APESuperHUD'
pod 'YLProgressBar'
pod 'SVPullToRefresh'
pod 'SwiftyStoreKit'
pod 'MBProgressHUD'
pod 'RxOptional'
pod 'RxCocoa', '3.0.0-beta.1'
pod 'RxSwift', '3.0.0-beta.1'
pod 'RxAlamofire', '3.0.0-beta.1'
pod 'RxSwiftExt', :git => 'https://github.com/RxSwiftCommunity/RxSwiftExt.git', :branch => 'swift3'
pod 'Action', '2.0.0-beta.1'
```

**Comment by kzaher** [comment] 2016-10-11 20:22
Ok, I guess we can close this for now.

**Closed by kzaher** 2016-10-11 20:22 UTC
