### ISSUE TITLE
RxCocoa error in Xcode 10 (`Cycle inside RxCocoa; building could produce unreliable results.`)

### ISSUE THREAD

**Issue by jdisho** [ReactiveX/RxSwift#1673] opened 2018-06-14 12:09 UTC
I get the following error, when I try to build a project that has RxCocoa as a dependency.  🤔

<img width="454" alt="screenshot 2018-06-14 at 14 03 57" src="https://user-images.githubusercontent.com/8223362/41411087-e82f970c-6fdb-11e8-8d71-38cff6d94295.png">

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

```
  4.0
```

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 10
```
**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment] 2018-06-14 17:49
Hi @jdisho ,

have no idea, PRs are welcome. I've created a new branch for [Xcode10](https://github.com/ReactiveX/RxSwift/tree/xcode10).

**Comment by carlosypunto** [comment] 2018-06-14 23:56
Appkit and UIKit has API changes in Swift 4.2. @kzaher, new branch [Xcode10](https://github.com/ReactiveX/RxSwift/tree/xcode10) will be for Swift 4.2?
@jdisho, has you try change swift version from 4.2 to 4.0 _RxCocoa_ target in Pod project?

**Comment by kzaher** [comment] 2018-06-16 21:19
@carlosypunto I think we should first figure out how to fix it, and if it's possible to make compatible changes with Xcode 9, then we'll use the same branch, otherwise we'll think about it more.

**Comment by carlosypunto** [comment] 2018-06-16 23:39
Ok @kzaher. I took a little while and did the update, basically the problem is with RxCocoa and RxExample, since RxSwift is Swift 4.2 code compatible. I could not pass the tests because (like in #1677 issue) runnin `./scripts/package-spm.swift` twice don't make the same content of `Sources/AllTestz/main.swift` so it will always modify the git working copy stoping the tests. I hope I have clarified something.

**Comment by hmlongco** [comment] 2018-06-17 13:09
Swift 4.2 implements SE-0206, which changes the way they make custom types conform to the Hashable protocol. It introduces a new Hasher struct that provides a randomly seeded, universal hash function to make this process easier:

Hasher uses a random seed every time it hashes an object, which means the hash value for any object is effectively guaranteed to be different between runs of your app.

**This in turn means that elements you add to a set or a dictionary are highly likely to have a different order each time you run your app.**

Thus I suspect that due to this, the function buildAllTestsTarget in ./scripts/package-spm.swift is no longer deterministic, and as such generates a different result every time that it's run.

**Comment by hmlongco** [comment] 2018-06-17 14:01
As mentioned in #1676, buildAllTestsTarget in ./scripts/package-spm.swift is no longer deterministic and as such generates a different set of results every time that it's run.

**package-spm.swift needs the following changes:**

```
-    for (name, methods) in reducedMethods {

+    for name in reducedMethods.keys.sorted() {
+        let methods = reducedMethods[name]!
```

and

```
-    for testCase in reducedMethods.keys {

+    for testCase in reducedMethods.keys.sorted() {
```

**Comment by hmlongco** [comment] 2018-06-17 14:30
PR #1676 `Add bag to dispose bag` includes this fix. After adding all checks passed.

**Comment by carlosypunto** [comment] 2018-06-18 09:10
Cool. If the _Xcode 10_ branch going to keep Swift 4.0 in future versions, is no longer necessary, the _develop_ branch is ready for _Xcode 10_ only using the next hook.

```
platform :ios, '9.0'
use_frameworks!

target 'TestRxSwift' do
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'develop'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'develop'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "4.0"
    end
  end
end
```

@kzaher, if you want _Xcode 10_ branch will be ready for Swift 4.2, I can make the conversion. Do I it?

**Comment by jdisho** [comment] 2018-06-20 20:13
I solved this issue by cleaning the build folder, clearing pods cache, re-install all pods, and then rebuilding.

**Comment by hmlongco** [comment] 2018-07-03 01:53
Just an FYI, but Xcode 10 beta 2 has a known issue regarding build cycles in the new build system. It's in the release notes.

**Comment by kzaher** [comment] 2018-07-21 16:55
As far as I can tell this works now.

**Comment by netbe** [comment] 2018-10-05 08:14
Hi, I am still getting this error on Xcode 10 and swift 4.2 using cocoapods:
```
 pod 'RxSwift', '4.3.1'
 pod 'RxCocoa', '4.3.1'
```

**Comment by nicktrienensfuzz** [comment] 2019-01-23 14:26
I still see this problem in 4.4.0, is there an actual fix? or is this just xcode being xcode?

**Comment by jdisho** [comment] 2019-01-23 18:48
>I solved this issue by cleaning the build folder, clearing pods cache, re-install all pods, and then rebuilding. 

Have you tried this? @nicktrienensfuzz 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gsbernstein** [comment] 2019-03-08 22:35
@jdisho that's only a temporary fix, it will happen again

**Comment by kzaher** [comment] 2019-03-09 13:25
Anybody has an idea how to solve this?

**Comment by freak4pc** [comment] 2019-03-09 18:25
It happens a lot and I don't see it being a RxSwift issue, but a Xcode/Swift issue. Proof of that being that cleaning derived data solves this.

**Comment by kzaher** [comment] 2019-03-09 21:39
I guess it could still be our issue somehow, but I have no idea what to do.

**Comment by yuriferretti** [comment] 2019-03-11 02:50
I think [this post](http://amro.co/diagnosing-dependency-cycle-between-targets-in-xcode-9-s-new-build-system) could help you. It states xcode 9 but you can take it as 9 or newer

**Comment by gsbernstein** [comment] 2019-03-11 18:36
Our organization has switched back to legacy build across the board due to seeing this in rxcocoa and rxswift to avoid clearing derived data every other build. Last time I saw it the cycle was rxoptional -> rx cocoa -> rxoptional.

**Comment by freak4pc** [comment] 2019-03-11 18:37
If this can be reproduced with RxOptional, I'd love to tackle this. 
I don't have the time to build 100 times until I find it, and in our project we don't experience this error. (Not using RxOptional, though)

**Comment by hmlongco** [comment] 2019-03-11 20:02
We had seen this previously when using CocoaPods and when the main project used RxSwift and RxCocoa and that project included a pod that also had RxSwift and RxCocoa as a dependency. The lead there is out, so I'm not sure if the team switched to legacy build or if they simply imported the code directly and dropped the pod.

At any rate it seemed to be related to the Compile Sources / Build Phases issue mentioned in the above link.

**Comment by boardmain** [comment] 2019-04-08 12:55
other problem

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "RxCocoa":
  In Podfile:
    RxCocoa (~> 5)

None of your spec sources contain a spec satisfying the dependency: `RxCocoa (~> 5)`.

**Comment by freak4pc** [comment] 2019-04-08 13:32
You’re probably directing your Podfile directly to master. If your remove that and target 4.5 you should be fine.

**Comment by freak4pc** [comment] 2019-04-14 16:57
@jdisho Or any other person with this issue, could any of you try Xcode 10.2 with the `develop` branch and see what's your status with it?

**Comment by jdisho** [comment] 2019-04-15 07:18
I can give this a try! @freak4pc

**Comment by freak4pc** [comment] 2019-04-30 10:13
@jdisho Had a chance?

**Comment by kzaher** [comment] 2019-05-06 09:28
Is anyone still experiencing this?

**Comment by jdisho** [comment] 2019-05-06 09:51
Personally, I can't and I am using Xcode 10.2.

**Comment by kzaher** [comment] 2019-05-06 10:37
Let's close this for now and if we encounter it in future, we can reopen it.

**Closed by kzaher** 2019-05-06 10:37 UTC
Labels: help wanted
