### ISSUE TITLE
 What is the performance of RxSwift?

### ISSUE THREAD

**Issue by tuyuan2012** [ReactiveX/RxSwift#2054] opened 2019-08-26 02:36 UTC
Our project uses the MVVM architecture and has recently been prepared to use RxSwift on a large scale. But We worry about the performance of RxSwift.
Thanks very much!

**Comment by freak4pc** [comment] 2019-08-26 12:20
Hey Tony. We don't offer any official comparative benchmark. There's a benchmark target in the RxSwift project which is meant only for validating any regressions in performance. 

RxSwift is used in high-scale production code by some of the biggest companies in the industry. If you have any specific performance concerns, you should run your own benchmark against your own use case to make sure it's a good fit.

Since this isn't an issue with RxSwift, I'm gonna close this for now. Thanks for understanding :) If you need additional help, Slack is available http://slack.rxswift.org

**Closed by freak4pc** 2019-08-26 12:20 UTC
