### ISSUE TITLE
failed to demangle superclass of CatchSink

### ISSUE THREAD

**Issue by naivalf27** [ReactiveX/RxSwift#2137] opened 2020-02-27 13:47 UTC
I have import RxSwift with SPM
My unit crash tests when I launch them (no problem with cocoapods)

Crash is in "Catch.swift" file in line: 163

log message : 
"failed to demangle superclass of CatchSink from mangled name '7RxSwift4SinkCyxG'"

I use SPM and Cocoapods and I want migrate to only SPM
I have Two Target and UnitTest

**Comment by freak4pc** [comment] 2020-02-27 13:50
Please open an new issue with all of the details in the template. We can really assist without them. 

Also, seems like this is a dupe of #2127

**Closed by freak4pc** 2020-02-27 13:50 UTC
