### ISSUE TITLE
.share() inconsistent in behavior

### ISSUE THREAD

**Issue by switchawk** [ReactiveX/RxSwift#1242] opened 2017-05-08 06:47 UTC
Hi guys, I want to discuss this scenario, regarding `share()` operator.
For this code:
```
let s = numbers1.scan(0) { prev, input in
    print("Scan")
    return prev+input
}.share()

s.subscribe(onNext: { x in
        print("\(x)")
    }, onCompleted: {
        print("-------------")
    })

s.subscribe(onNext: { x in
    print("\(x)")
}, onCompleted: nil)
```

This input ("A"):
```
let numbers1 = Observable<Int>.create { observer in
    let start = getStartNumber()
    observer.onNext(start)
    observer.onNext(start+1)
    observer.onNext(start+2)
    observer.onCompleted()
    return Disposables.create()
}
```
Will result with:
```
Scan
1
Scan
3
Scan
6
-------------
Scan
Scan
Scan
```
However this input ("B"):
```
let numbers1 = Observable.from([1,2,3])
```
Will result with this:
```
Scan
1
Scan
3
Scan
6
-------------
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.2.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  8.3.2
```

**Installation method**:
  - [X] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [X] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment] 2017-05-09 08:44
Hi @switchawk ,

This is a dupe of #1111 and #1155.

This is next thing to solve on my list. The problem isn't in us changing it in this repo. 

Problem is figuring out how will we keep consistent this behavior with other implementations. I'll need to open issues in RxJs and RxJava repos probably.

But yes, we'll improve this.

**Comment by kzaher** [comment] 2017-05-09 08:48
If you want a temporary workaround for this, just add `subscribeOn(CurrentThreadScheduler.instance)` in front of `share`.

```swift
let s = numbers1.scan(0) { prev, input in
        print("Scan")
        return prev+input
}.subscribeOn(CurrentThreadScheduler.instance).share()
```

**Comment by RafaelPlantard** [comment] 2017-05-16 11:35
Any news @kzaher?

**Comment by kzaher** [comment] 2017-05-16 16:52
Hi @RafaelPlantard ,

this is the next thing on my list. I'm on a business trip in China until the end of this week. I will only do CRs until I return from the trip.

It's little hard to do a lot of things in parallel :)

**Comment by RafaelPlantard** [comment] 2017-05-16 18:06
Thanks @kzaher

**Comment by kzaher** [comment] 2017-05-29 12:58
Hi guys,

As far as I can tell, #1275 should fix this. Let me know if it doesn't.

**Closed by kzaher** 2017-05-29 12:58 UTC
