### ISSUE TITLE
Manual integration of XCFrameworks in Test Target

### ISSUE THREAD

**Issue by odanu** [ReactiveX/RxSwift#2292] opened 2021-02-12 08:17 UTC
**Short description of the issue**:

I am having an issue with integrating manually the XCFrameworks in the Test Target.

**Expected outcome**:

Be capable to run tests using RxTests and RxBlocking.

**What actually happens**:

Getting errors:

```
Showing Recent Messages
Ld: warning: ignoring file Frameworks/RxBlocking.xcframework/ios-arm64_armv7/RxBlocking.framework/RxBlocking, missing required architecture x86_64 in file Frameworks/RxBlocking.xcframework/ios-arm64_armv7/RxBlocking.framework/RxBlocking (2 slices)ignoring file Frameworks/RxTest.xcframework/ios-arm64_armv7/RxTest.framework/RxTest, missing required architecture x86_64 in file Frameworks/RxTest.xcframework/ios-arm64_armv7/RxTest.framework/RxTest (2 slices)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.1.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  12.4
```

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [x] Manual XCFrameworks

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by odanu** [comment] 2021-02-12 08:20
Here are some screenshots from the Main and Test target configuration.
<img width="979" alt="errors" src="https://user-images.githubusercontent.com/1110408/107744685-d03aef80-6d1b-11eb-9878-059d11f2529e.png">
<img width="1278" alt="warning" src="https://user-images.githubusercontent.com/1110408/107744707-d7fa9400-6d1b-11eb-97cf-95543e894535.png">
<img width="1090" alt="test target" src="https://user-images.githubusercontent.com/1110408/107744709-d92bc100-6d1b-11eb-8043-56b6f7ac80fa.png">
<img width="573" alt="main target" src="https://user-images.githubusercontent.com/1110408/107744712-d9c45780-6d1b-11eb-840f-d815f0c277be.png">

**Comment by odanu** [comment] 2021-02-12 16:04
Played with the configurations today and nothing helped. I updated the screenshots with the last state of the dependency integration picture... still having the same issue.
Worth to mention that we are using Standard Architecture, no `Valid Architecture` setting is there `Excluded Arcchitecture` is also empty. Building `Active Architecture Only` for the Test target.

**Comment by odanu** [comment] 2021-02-12 19:38
Attaching a small reproducible project.
Root/Frameworks folder contains placeholders for the frameworks.

[rxbug.zip](https://github.com/ReactiveX/RxSwift/files/5973974/rxbug.zip)

**Comment by odanu** [comment] 2021-02-13 20:31
I managed to find a workaround. Since xcode tools have difficulties selecting the right architecture slice, I just manually removed the `ios-arm64_armv7` slice from XCFrameworks.
I though it is safe to do it, since I only deleted the slices from RxBlocking and RxTest - frameworks which are only used for unit testing in our project and we run the tests only on simulator.

**Comment by freak4pc** [comment] 2021-02-13 20:32
That seems like a reasonable solution but I'm confused with why Xcode itself didn't get rid of the slices it didn't need. This is literally what the XCFramework format is meant for 🤔

**Comment by odanu** [comment] 2021-02-13 20:34
Obviously, it's either an XCode bug or we are missing something.

**Comment by freak4pc** [comment] 2021-02-13 20:36
I built it on an M1 Mac, which I wonder if related. 
If you're curious and want to try, install this:
https://github.com/unsignedapps/swift-create-xcframework

(using `mint install unsignedapps/swift-create-xcframework@v1.3.0`) 

And run:
```sh
 swift create-framework --output xcframeworks RxTest RxBlocking
```

I'm wondering if building locally will matter at all.

**Comment by odanu** [comment] 2021-02-13 21:01
>  If you're curious and want to try, install this:

I am curious and would be happy to help, but I don't have `mint` installed and it looks like it's not a simple step, which I would like to avoid.
Installed the tool manually as described in the specific section using `make install`... but than, I had issues executing the command.

**Comment by freak4pc** [comment] 2021-02-13 21:12
It seems it's just:

```sh
brew tap mint-lang/mint-lang
brew install mint-lang
```

Unless you don't have Homebrew installed at all :)

**Comment by odanu** [comment] 2021-02-13 21:18
Hmm I tried the other one before... 
‘’’
brew tap mint-lang/mint-lang
brew install mint-lang
‘’’
But it didn’t work.
Will try your suggestion tomorrow ;)

**Comment by freak4pc** [comment] 2021-02-13 21:22
Yeah I got confused as well, that's a programming language called `mint` as opposed to the package manager called `Mint` 🤦 

Thanks!

**Comment by odanu** [comment] 2021-02-14 07:31
I managed to generate the xcframeworks, but  using `swift create-xcframework...`, I guess it was a typo on your side.
But in the end, the result was the same. Same slices  were included in the package and XCode couldn't pick the right one.

**Comment by freak4pc** [comment] 2021-02-28 19:52
I'm not seeing anything that we can do here since it seems like an issue with the compiler/linker choosing the wrong slices, which isn't something we can affect. My instinct would be to file a bug on https://bugs.swift.org . I'd do so myself but I can't easily reproduce with your sample project (getting plist-related compilation errors).

**Comment by agruchala** [comment] 2021-03-05 12:32
You can go back to fat frameworks done by lipo and:
You can try to set Validate Workspace on build settings to Yes (NOT Yes(Error)) try again. It will change errors to warnings for multiple archs.

**Comment by sushant40** [comment] 2021-03-08 06:54
I got similar issues that im thinking of filing a separate bug on.

When i build Rx Swift with carthage 0.37 i get xcode 12.4 complaining about missing architectures for simulator (intel).
When i use the precompiled framework thats included with rxswift 6.1.0, xcode complains about linker issues even thrugh my search path is setup.

Will link the bug that i am going to create once i well and truly give up.

**Comment by freak4pc** [comment] 2021-03-14 18:40
Sorry, but have to close this mainly due to the fact we can't possibly fix Apple's tooling.
If there's an advancement in this issue from Apple's side that requires us doing something, I'm happy to reopen. 

Thanks!

**Closed by freak4pc** 2021-03-14 18:40 UTC

**Comment by Svetoslav** [comment] 2021-03-22 13:04
This indeed seems to be an Apple tooling issue. However, in case someone ends up on this issue report in the search of a workaround: a tad simpler to manage workaround alternative to @odanu's workaround to remove the non `-simulator` subfolder in the respective `.xcframework` folders, is to change in the build settings of your test target FRAMEWORK_SEARCH_PATHS, so that you have the full path to the `-simulator` folder, e.g. `$(PROJECT_DIR)/Carthage/Build/RxTest.xcframework/ios-arm64_i386_x86_64-simulator`, precede the inherited general project search paths:
<img width="519" src="https://user-images.githubusercontent.com/35994/111993295-1f482180-8b1f-11eb-9f35-5d01b3f13f18.png">

It achieve effectively the same result—cluing in Xcode where to find the simulator slices, but without the need for manual changes of the `Carthage/Build` contents.
