### ISSUE TITLE
"sample" operator doesn't emit onCompleted if sampler has already completed.

### ISSUE THREAD

**Issue by k5n** [ReactiveX/RxSwift#794] opened 2016-07-14 04:55 UTC
[ReactiveX Sample](http://reactivex.io/documentation/operators/sample.html) says that onCompleted should be emmited when an Observable completes.

Code example:

```swift
func triggerObservable() -> Observable<Void> {
  return Observable.create { observer in
    NSLog("start trigger")
    sleep(2)
    observer.onNext(())
    sleep(2)
    observer.onNext(())
    sleep(2)
    observer.onNext(())
    sleep(2)
    observer.onCompleted()
    return NopDisposable.instance
  }
}

func valueObservable() -> Observable<Int> {
  return Observable.create { observer in
    NSLog("start value")
    observer.onNext(0)
    sleep(3)
    observer.onNext(1)
    sleep(4)
    observer.onNext(2)
    sleep(2)
    observer.onCompleted()
    return NopDisposable.instance
  }
}

let scheduler = ConcurrentDispatchQueueScheduler(globalConcurrentQueueQOS: .Default)
let sampler = triggerObservable().subscribeOn(scheduler)
_ = valueObservable().subscribeOn(scheduler).sample(sampler).subscribe(
  onNext: { value in
    NSLog("value = \(value)")
  },
  onCompleted: {
    NSLog("onCompleted")
  })
```

Expected:

2016-07-14 12:12:45.058 MyApp[302:18224] start trigger
2016-07-14 12:12:45.058 MyApp[302:18179] start value
2016-07-14 12:12:47.152 MyApp[302:18224] value = 0
2016-07-14 12:12:49.223 MyApp[302:18224] value = 1
2016-07-14 12:12:53.334 MyApp[302:18224] value = 2
2016-07-14 12:12:54.xxx MyApp[302:18179] onCompleted

Actually:

2016-07-14 12:12:45.058 MyApp[302:18224] start trigger
2016-07-14 12:12:45.058 MyApp[302:18179] start value
2016-07-14 12:12:47.152 MyApp[302:18224] value = 0
2016-07-14 12:12:49.223 MyApp[302:18224] value = 1
2016-07-14 12:12:53.334 MyApp[302:18224] value = 2

Suggest:

```swift
class SamplerSink<O: ObserverType, ElementType, SampleType where O.E == ElementType>
    // ...
{
    // ...
    func _synchronized_on(event: Event<E>) {
        // ...
        case .Completed:
            if let element = _parent._element {
                _parent._element = nil
                _parent.forwardOn(.Next(element))
            }

            _parent.lock()
            let atEnd = _parent._atEnd
            _parent._samplerEnded = true
            _parent.unlock()

            if _atEnd {
                _parent.forwardOn(.Completed)
                _parent.dispose()
            }
        }
}

class SampleSequenceSink<O: ObserverType, SampleType>
    // ...
{
    // ...
    private var _samplerEnded = false
    // ... 
    func _synchronized_on(event: Event<Element>) {
        // ...
        case .Completed:
            lock()
            _atEnd = true
            let samplerEnded = _samplerEnded
            unlock()

            _sourceSubscription.dispose()
            if samplerEnded {
                forwardOn(.Completed)
            }
        }
    }
}
```

**Comment by kzaher** [comment] 2016-07-16 16:14
Hi @k5n ,

It seems to me that this is not a bug. If you check out rxjs implementation:
```
Observable.interval(100).sample(Observable.interval(400).take(2)).subscribe(function(x) { console.log(x); }, function() {}, function() { console.log("completed"); })
```
this won't complete.

I'll post issue on ReactiveX website and try to figure out which one is the reference implementation, or is there one. RxJs, and Rx.NET behave this way.

@k5n I'm kind of curious, in what situation does this create issues for you?

**Comment by k5n** [comment] 2016-07-19 03:00
Hi @kzaher , thanks for your reply.

I tested RxJava.

```java
Observable.interval(100, TimeUnit.MILLISECONDS, Schedulers.newThread())
    .sample(Observable.interval(400, TimeUnit.MILLISECONDS, Schedulers.newThread()).take(2))
    .subscribe(new Observer<Long>() {
        @Override
        public void onCompleted() {
            System.out.println("onCompleted");
        }
        @Override
        public void onError(Throwable error) {
        }
        @Override
        public void onNext(Long value) {
            System.out.println("onNext: " + value);
        }
    });
```
This completes. But it seems that onCompeted is emmited when the sampler completes.
See [RxJava source code](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OperatorSampleWithObservable.java).

> @k5n I'm kind of curious, in what situation does this create issues for you?

I have never encounter any situations that this creates issues. I just noticed and reported.

**Comment by kzaher** [comment] 2016-07-19 22:32
Hi @k5n ,

yeah, thnx for reporting this. It's always great to know all of the problems.

This seemed to me like a more general issue then just this misalignment. The problem is that we have more or less two parallel slightly inconsistent versions.

I think that there is probably a small chance there is some definite reference implementation we can count on, and it will probably take some time for all implementations to converge, but I think that even what we have now is a step in a right direction :)

The good thing is that it isn't causing serious issues for you.

I would probably wait a bit and see will there be any response on issues I've posted in other projects. If there won't be any, then I guess we'll probably close this issue. Not sure what else to do since this is behaving as intended as far as I can tell.

**Comment by kzaher** [comment] 2016-08-09 21:23
Not sure what to do with this :)

There still aren't any clear consensus here. We can revise this in future when it's clear what needs to happen in that scenario. It shouldn't cause any significant issues meanwhile.

**Closed by kzaher** 2016-08-09 21:23 UTC
