### ISSUE TITLE
XCTAssertEqual support for Recorder<Event<Optional<T>>>

### ISSUE THREAD

**Issue by jasminsuljic** [ReactiveX/RxSwift#1385] opened 2017-08-17 21:00 UTC
**Short description of the issue**:

XCTAssertEqual does not work with Recorded<Event<Optional<T>>> when comparing events due to missing XCTAssertEqual implementation

**Expected outcome**:

XCTAssertEqual override should probably exist to deal with observables which emits optional values.

**What actually happens**:

  Compile error: ``` TestsExample.swift:98:9: Cannot invoke 'XCTAssertEqual' with an argument list of type '([Recorded<Event<Bool?>>], [Recorded<Event<Bool?>>])' ```

**Self contained code example that reproduces the issue**:

```swift
import XCTest

import RxSwift
import RxTest
import RxBlocking

class RXSwiftFeatureExample: XCTestCase {
    
    func test_rxswift_asset_equal_optional () {
        
        let scheduler = TestScheduler(initialClock: 0)
        let disposeBag = DisposeBag()
        
        let observable = scheduler.createColdObservable([
            next(0, nil),
            next(0, false)
            ])
        
        let events = [
            next(0, nil),
            next(0, false)
        ]
        
        let observer = scheduler.createObserver(Optional<Bool>.self)
        
        scheduler.start()
        
        observable.subscribe(observer).disposed(by: disposeBag)
        // Compile error
        XCTAssertEqual(observer.events, events)
    }
    
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

- RxSwift (3.6.1)
- RxTest (3.6.1)
- RxBlocking (3.6.1)

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 8.3.3 (8E3004b)
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment] 2017-08-17 21:26
I believe this is a duplicate of this: https://github.com/ReactiveX/RxSwift/pull/1384

**Closed** 2017-08-19 20:46 UTC
