### ISSUE TITLE
on iOS 7 has problem

### ISSUE THREAD

**Issue by sugarwyc** [ReactiveX/RxSwift#388] opened 2016-01-06 06:25 UTC
Xcode 7.2, create new project With `Single View Application` 
![7bd4d182-a991-43c4-87f7-7d47220d26ac](https://cloud.githubusercontent.com/assets/5518603/12136226/6aabc206-b480-11e5-913d-31d9b26aa3eb.png)
![541eecdc-d172-4e2c-8187-bb843952f1b9](https://cloud.githubusercontent.com/assets/5518603/12136261/cfe7b300-b480-11e5-9e68-702138ae8597.png)

run on iPod 5 with iOS 7.0  
tap '++' button,label display '2'  
tap again, no effect

**Comment by sugarwyc** [comment] 2016-01-06 06:50
![781cf1c8-0c18-4dd9-8c68-cccca2608a8e](https://cloud.githubusercontent.com/assets/5518603/12136533/d6ecc778-b483-11e5-97ac-f7ffd5f811b8.png)
![img_0003](https://cloud.githubusercontent.com/assets/5518603/12136594/64001f2a-b484-11e5-87f7-cd767e4b059e.jpg)

run `RxExample-iOS-no-module` on iPod 5(iOS 7.0)  
tap 'Simple validation', `EXC_BAD_ACCESS`

**Comment by kzaher** [comment] 2016-01-06 12:14
Hi @sugarwyc ,

I believe there are serious problems with Swift compiler on iOS7. This looks like a duplicate of https://github.com/ReactiveX/RxSwift/issues/69.

We've done what ever we can to support iOS7, but we do rely on Swift compiler to generate correct assembler. 

If Swift compiler doesn't work properly on iOS 7 (and that seems to be the case according to informations that are available to me), then I don't think it's realistic for us to use tricks so that compiler can generate correct code.

¯\\\_(ツ)\_/¯ 

I mean we technically do support iOS7, but Swift compiler has serious issues there :/

**Comment by bontoJR** [comment] 2016-02-16 15:53
I think this can be close, if anyone has a similar problem, please re-open the issue and give more details.

**Closed by bontoJR** 2016-02-16 15:53 UTC
Labels: wontfix
