### ISSUE TITLE
launch crash（Xcode13.2.1,iPhone12.5.5(iPhone6P/iPhone6)） 

### ISSUE THREAD

**Issue by GPF253904828** [ReactiveX/RxSwift#2393] opened 2022-01-18 10:35 UTC
dyld: Symbol not found: ___chkstk_darwin
Referenced from: /private/var/containers/Bundle/Application/328F0644-9ACE-4F31-A547-E9F4950A2F9F/XXX.app/Frameworks/libswift_Concurrency.dylib (which was built for iOS 13.0)
Expected in: /usr/lib/libSystem.B.dylib
in /private/var/containers/Bundle/Application/328F0644-9ACE-4F31-A547-E9F4950A2F9F/XXX.app/Frameworks/libswift_Concurrency.dylib

**Comment by freak4pc** [comment] 2022-01-18 10:36
Please attach a reproducible project

**Comment by freak4pc** [comment] 2022-01-18 13:29
> Maybe it's because they used Swift Concurrency (#2367 , RxSwift version: 6.5), it supports iOS 13+ only, without updates in Podfile. So you may update Podfile, like `s.ios.deployment_target = '13.0'` with RxSwift version 6.5 @freak4pc For you @GPF253904828 , I suggest you using RxSwift 6.2.
> 
> ref: [Alamofire/Alamofire#3529](https://github.com/Alamofire/Alamofire/issues/3529)

Hey @iTofu - 
That's not actually true. Only the concurrency feature are iOS 13 and up, as indicated by their availability clauses. 
Also, note they're only compiled under Swift 5.5.2 and up (Xcode 13.2), so there should be no conflict: 
https://github.com/ReactiveX/RxSwift/blob/main/RxSwift/Observable+Concurrency.swift#L9-L12

I believe the issue here is something else, which is why I'm asking for a repro project.

**Comment by freak4pc** [comment] 2022-01-18 13:35
Could you try linking libSwift_concurrency as optional? @GPF253904828 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/605076/149947350-4361f9dc-4302-447b-8c76-05ff0c4dbdc1.png">

**Comment by iTofu** [comment] 2022-01-18 13:35
@freak4pc , thank you for you reply.
But I think the code you said doesn't work as expected, because Swift 5.5.2 can also run on iOS 11 devices.
In fact, my project crashes on a iOS 11 device and it's because of RxSwift 6.5……

**Comment by freak4pc** [comment] 2022-01-18 13:36
@iTofu, it's a combined thing :) 
You have the compiler directive saying if it can be built (Swift 5.5.2 and up) - that's working
Then, you have an availability clause.

So, if you compiler for iOS 11 and Xcode 13.2.1 - that code would be built by RxSwift, but you won't be able to use it since it's iOS 13 and up only.

**Comment by freak4pc** [comment] 2022-01-18 13:43
@iTofu @GPF253904828 
This seems to be a bug on Apple's side affecting many many other projects :( 

I'm not entirely sure if there's anything I can suggest doing aside for sticking with Xcode 13.1 or RxSwift 6.2 at the moment:
https://forums.swift.org/t/swift-concurrency-back-deploy-issue/53917/23

**Comment by iTofu** [comment] 2022-01-18 13:49
@freak4pc 
Yes I see, you may be right.
And I decided to stay on the RxSwift 6.5 for now.

**Comment by serges147** [comment] 2022-01-19 11:09
Exactly the same issue with GRDB pod - they adopted recently async/await as well, and now we stuck with older version (hopefully until Apple resolve the issue).

**Comment by freak4pc** [comment] 2022-01-19 11:15
> Exactly the same issue with GRDB pod - they adopted recently async/await as well, and now we stuck with older version (hopefully until Apple resolve the issue).

Yup, saw it as well. I'm hopeful Apple will (pardon my French) get their s#!t together 🤷‍♂️

**Comment by GPF253904828** [comment] 2022-01-19 11:26
Package
RxSwift                   version5.1.1 -> branch-main
RxDataSources      version4.0.1 -> branch-main
I modified the version and encountered a crash,
Restore the version back to solve the crash.

**Comment by freak4pc** [comment] 2022-01-19 11:27
I'm not sure how RxSwift 5.x is relevant here. The issue related to 6.5.

**Comment by svenmuennich** [comment] 2022-02-10 16:48
According to the [Xcode Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_3-release-notes#Updates-in-Xcode-13.3-Beta) this bug is fixed in Xcode 13.3 Beta:
> ### Resolved Issues
>
> * Apps that use back-deployed Swift Concurrency on operating systems prior to macOS 10.15, iOS 13, tvOS 13, or watchOS 6 no longer crash on launch. (87789769)

**Comment by freak4pc** [comment] 2022-02-10 16:53
> According to the [Xcode Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_3-release-notes#Updates-in-Xcode-13.3-Beta) this bug is fixed in Xcode 13.3 Beta:
> 
> > ### Resolved Issues
> > 
> > * Apps that use back-deployed Swift Concurrency on operating systems prior to macOS 10.15, iOS 13, tvOS 13, or watchOS 6 no longer crash on launch. (87789769)

Only left to cross fingers it's released soon. If anyhow can check it's fixed on the beta that'd be great. Thanks!

**Comment by serges147** [comment] 2022-02-23 14:49
With XCode 13.3 beta 3 (13E5104i) my macOS test app (linked with Rx 6.5.0) is working fine on macOS 10.12 - with XCode 13.2 it crashed. So, looks like will be fixed in 13.3 release (at least on mac)...

**Comment by iTofu** [comment] 2022-02-24 04:36
Nice...

Sergei ***@***.***>于2022年2月23日 周三下午10:50写道：

**Comment by freak4pc** [comment] 2022-04-30 20:09
> I just verified that this issue is indeed fixed by Xcode 13.3.1.
> 
> Based on the information given [Alamofire/Alamofire#3590](https://github.com/Alamofire/Alamofire/pull/3590) which addresses a similar issue in _Alamofire_ it looks like Xcode 13.3.0 does not fix this issue, only 13.3.1.
> 
> That being said I like the workaround applied there which is requiring Swift >= 5.6 for concurrency support. This makes running into the issue described here much less likely as one would have to update Xcode which probably results in using at least 13.3.1. What do you think?

It's a possible solution, yet a bit breaking. I don't mind applying it, theoretically.

**Comment by freak4pc** [comment] 2022-06-03 19:36
Applied @svenmuennich's suggestion in e0ab8c4e

**Closed by freak4pc** 2022-06-03 19:36 UTC
