### ISSUE TITLE
No signal is triggered when a value is assigned directly for UITextField

### ISSUE THREAD

**Issue by YariZhang** [ReactiveX/RxSwift#1682] opened 2018-06-22 10:02 UTC
**Short description of the issue**:

  No signal is triggered when a value is assigned directly for UITextField.

**Expected outcome**:

  `let phoneResults = phoneTf.rx.text.orEmpty
            .map { $0.isMatch("^1\\d{10}$") }
            .share(replay: 1)`

  `phoneResults.bind { [weak self] (valid) -> Void in
            if !valid && self!.phoneTf.text!.count > 11 {
                self?.phoneTf.text = self!.phoneTf.text![0..<11]
            }
            }.disposed(by: disposeBag)`

To this : 
`self?.phoneTf.text = self!.phoneTf.text![0..<11]`

 I give it a value that satisfies the condition ,it should trigger the correct signal to make the condition true.
  
**What actually happens**:

I set "self?.phoneTf.text = self!.phoneTf.text![0..<11]" but phoneResults is still invalid,  it seems "=" cannot trigger signal. What can I do？Thanks!

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  RxSwift 4.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 9.3.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**Comment by kzaher** [comment] 2018-06-23 20:21
Hi @YariZhang ,

this is duplicate of #1646

**Closed by kzaher** 2018-06-23 20:21 UTC
