### ISSUE TITLE
Problem in my framework which based RxSwift

### ISSUE THREAD

**Issue by Blackvsion** [ReactiveX/RxSwift#2375] opened 2021-11-03 07:48 UTC
**Short description of the issue**:

I'm developing a swift framework that depends on RxSwift, it works well when debug, so I package it (fastlane -> carthage)  and upload to cocoapods. Then I create a new Project and try my framework by cocoapods. However it crash At
```
RxSwift.PublishSubject line 93:
self.lock.performLocked { self.synchronized_subscribe(observer) }    ⚠️Thread 1: signal SIGABRT
```

**Expected outcome**:

  It can run well with framework

**What actually happens**:

  It crash

**Self contained code example that reproduces the issue**:

I try a simple code and It also can not run well
```swift
  code goes here
  
import UIKit
import RxSwift
import RxCocoa

public class BVTestView: UIView {
    var roomData: PublishSubject<Int> = PublishSubject()
    var mapViewW: PublishSubject<CGFloat> = PublishSubject<CGFloat>()
    var mapViewH: PublishSubject<CGFloat> = PublishSubject<CGFloat>()
    private let disposeBag: DisposeBag = DisposeBag.init()
    public init() {
        super.init(frame: .zero)
        initView()
    }
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    func initView() {
        self.backgroundColor = .red
        Observable.zip(mapViewW, mapViewH, roomData)
            .subscribe { (width, height, data) in
                print("\(width) == \(height) == \(data)")
            }
            .disposed(by: disposeBag)
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 ```
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'RxRelay', '6.2.0'
```

**Platform/Environment**

  - [ √] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ √] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 13.0
```

**Installation method**:
  - [ √] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [ √] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ √] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by Blackvsion** [comment] 2021-11-03 07:51
I run 
```
po self.lock
```
in terminal when it crash

just this:
```
error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=2, address=0x11a0080000).
The process has been returned to the state before expression evaluation.
```

**Comment by freak4pc** [comment] 2021-11-03 07:55
Hey, 
Don't think we'll be able to help without a fully reproducible example here.

But, generally it sounds related to something with Carthage or some configuration and it's not something we directly support unless there's a more widespread issue.

**Comment by freak4pc** [comment] 2021-11-03 09:25
Hey, I'm sorry to be the bearer of bad news here - but if the project works fine when running before packaging it with fastlane, this is an archiving/configuration issue, and that's unfortunately out-of-scope to the support we provide here.

If this was an issue specific to RxSwift (not just to your specific configuration) it would've been easier to look at but otherwise it's a bit tricky, I'm not too sure I can help beyond this.

**Comment by Blackvsion** [comment] 2021-11-03 10:00
> Hey, I'm sorry to be the bearer of bad news here - but if the project works fine when running before packaging it with fastlane, this is an archiving/configuration issue, and that's unfortunately out-of-scope to the support we provide here.
> 
> If this was an issue specific to RxSwift (not just to your specific configuration) it would've been easier to look at but otherwise it's a bit tricky, I'm not too sure I can help beyond this.

@freak4pc Hi, have you tried my case? is it run well in your side? I remove all other pods, leaving only 'RxSwift', 'RxCocoa', 'RxRelay' and try again, it also crash('BVHttp', '0.1.8'). 

This framework is very important to me, can you teach me how to configure my project and how to archive a framework based on RxSwift? Any specific configuration?

**Comment by danielt1263** [comment] 2021-11-03 11:27
I tried including the 'BVHTTP' pod in a project. The project ran.

**Comment by Blackvsion** [comment] 2021-11-03 11:32
> I tried including the 'BVHTTP' pod in a project through cocoapods. The project ran.

@danielt1263  Hi, have you tried 'BVTestView' like this?
```
let testView = BVTestView.init()
testView.frame = CGRect.init(x: 0, y: 0, width: 375, height: 375)
self.view.addSubview(testView)
```
and see a red view ?

**Comment by danielt1263** [comment] 2021-11-03 11:42
No I did not. I had no idea that I should try that. I have tried it now and the code crashes. Since the pod doesn't include any code, only a framework, I am unable to help determine the problem.

**Comment by Blackvsion** [comment] 2021-11-03 13:02
> No I did not. I had no idea that I should try that. I have tried it now and the code crashes. Since the pod doesn't include any code, only a framework, I am unable to help determine the problem.

@danielt1263 Hi,
sorry about that I can not show you the project, but all about the way to archive the framework is on above, include the code, you can try it by yourself, it's very simple, just one file.

**Comment by danielt1263** [comment] 2021-11-03 13:41
Sorry. I don't know enough about how to setup a CocoaPod to be of use. Nor do I know anything about Fastlane or Carthage.

**Comment by freak4pc** [comment] 2021-11-03 13:41
I'm sorry @Blackvsion - this is a bit out of scope or a RxSwift GitHub issue.
I suggest joining our slack and trying to find help there. http://slack.rxswift.org

**Closed by freak4pc** 2021-11-03 13:41 UTC

**Comment by Blackvsion** [comment] 2021-11-04 01:23
> Sorry. I don't know enough about how to setup a CocoaPod to be of use. Nor do I know anything about Fastlane or Carthage.

@danielt1263  It doesn't matter. Anyway, thanks bro.
