### ISSUE TITLE
Swift 3.0 - xcode 8- getting this error

### ISSUE THREAD

**Issue by anafinotti** [ReactiveX/RxSwift#899] opened 2016-09-20 01:19 UTC
![screen shot 2016-09-19 at 8 10 43 pm](https://cloud.githubusercontent.com/assets/5528817/18654394/665d12b8-7ea6-11e6-9ddd-66dce14c97bd.png)

**Comment by HotWordland** [comment] 2016-09-20 08:27
I have too

**Comment by AleLudovici** [comment] 2016-09-20 13:55
I was getting this error with the 3.0.0-alpha.1 version of the pod (Xcode 8 GM). Updating the pod to `3.0.0-beta.1` fixed this issue for me.

**Comment by peterlondon1** [comment] 2016-09-20 17:34
I have too with 3.0.0-beta.1

**Comment by jondwillis** [comment] 2016-09-20 21:26
Use 3.0.0 and Cocoapods 1.1.x

**Comment by HotWordland** [comment] 2016-09-21 00:46
@AleLudovici I used 3.0.0-beta.1 in CocoaPods(1.1.x) and Xcode8 version (not GM).

**Comment by leizh007** [comment] 2016-09-29 13:17
<img width="349" alt="qq20160929-0 2x" src="https://cloud.githubusercontent.com/assets/7850978/18955419/fbc022d8-8689-11e6-987b-4bcdba9d5985.png">
I am using cocoapods: 1.1.0.beta.2
Xcode: Version 8.0 (8A218a)
Swift 3.0

**Comment by kzaher** [comment] 2016-09-29 17:15
@leizh007 ,

please try with `1.1.0.rc.2`

**Comment by kzaher** [comment] 2016-10-01 22:06
Ok guys, this is a dupe of #899, let's continue discussion there.

**Closed by kzaher** 2016-10-01 22:06 UTC
