### ISSUE TITLE
Implement DelegateProxyType for pure swift delegate

### ISSUE THREAD

**Issue by mobilinked** [ReactiveX/RxSwift#1460] opened 2017-10-19 21:37 UTC
**Short description of the issue**:

  "@objc" has been added to a pure swift delegate to implement DelegateProxyType

**Expected outcome**:

  Pass xcode compiling without adding "@objc"

**What actually happens**:

  We have to change the implementations of some DelegateProxyType when migrating macOS project to Swift 4 and using RxSwift 4.0.0
  By ref the implementation of RxTextFieldDelegateProxy at https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/macOS/NSTextField%2BRx.swift

  Compiling failed with two errors: 
  - "super.init" cannot be called outside of an initializer 
  - Type "..." does not conform to protocol 'DelegateProxyType" (because of not implementing forwardToDelegate ad setForwardToDelegate) 

  Our temp solution is to add "@objc" to the interface to pass compiling - our expectation is to use PURE swift. 
```swift
@objc protocol TestControlDelegate: AnyObject {
```
  
**Self contained code example that reproduces the issue**:

```swift
import Cocoa
import RxSwift
import RxCocoa

protocol TestControlDelegate: AnyObject {
    func delegateDoSomething()
}
class TestControl: NSView {
    weak var delegate: TestControlDelegate? = nil
}

extension TestControl: HasDelegate {
    public typealias Delegate = TestControlDelegate
}

class TestControlProxy
    : DelegateProxy<TestControl, TestControlDelegate>
    , DelegateProxyType
    , TestControlDelegate {
    
    fileprivate let _imageSubject = PublishSubject<Void>()
    fileprivate weak var _control: TestControl? = nil
    
    //#MARK: DelegateProxy
    init(parentObject: TestControl) {
        self._control = parentObject
        super.init(parentObject: parentObject, delegateProxy: TestControlProxy.self)
    }
    
    public static func registerKnownImplementations() {
        self.register { TestControlProxy(parentObject: $0) }
    }
    
    func delegateDoSomething() {
        _imageSubject.on(.next(()))
//        forwardToDelegate()?.delegateDoSomething()
    }
}
```
  
**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  4.0.0

**Platform/Environment**

  - [ ] macOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  

**Xcode version**:

```
  9.0.1
```

**Installation method**:
  - [ ] CocoaPods

**Comment by kzaher** [comment] 2017-10-19 21:39
This is a dupe of #1460.

This was my last comment there https://github.com/ReactiveX/RxSwift/issues/1442#issuecomment-337350983

**Comment by mobilinked** [comment] 2017-10-19 21:58
Thanks @kzaher 

No lucky, I changed the RxCocoa code by following #1460, "@objc" is still needed, and even worse with an additional compiling error "Using '...' as a concrete type conforming to protocol 'NSObjectProtocol' is not supported"

Would you please help to check what's the problem? 

```swift
protocol TestControlDelegate: NSObjectProtocol {
    func delegateDoSomething()
}
class TestControl: NSView {
    weak var delegate: TestControlDelegate? = nil
}

extension TestControl: HasDelegate {
    public typealias Delegate = TestControlDelegate
}

class TestControlProxy
    : DelegateProxy<TestControl, TestControlDelegate>
    , DelegateProxyType
    , TestControlDelegate {
    
    fileprivate let _imageSubject = PublishSubject<Void>()
    fileprivate weak var _control: TestControl? = nil
    
    //#MARK: DelegateProxy
    init(parentObject: TestControl) {
        self._control = parentObject
        super.init(parentObject: parentObject, delegateProxy: TestControlProxy.self)
    }
    
    public static func registerKnownImplementations() {
        self.register { TestControlProxy(parentObject: $0) }
    }
    
    func delegateDoSomething() {
        _imageSubject.on(.next(()))
//        forwardToDelegate()?.delegateDoSomething()
    }
}
```

**Comment by tarunon** [comment] 2017-10-20 04:11
Hi there,
We cannot use pure swift protocol in conditional type parameter. It's not supported on swift 4.0.

```swift
protocol Animal {}
protocol Cat: Animal {}
@objc protocol Plants {}

struct Pass<T> {}
struct Fail<T: Animal> {}

Pass<Animal>.self // OK
Pass<Cat>.self // OK
Fail<Animal>.self // Compile error: Using 'Animal' as concrete type conforming to protocol 'Animal' is not supported
Fail<Cat>.self // Compile error:Using 'Cat' as concrete type conforming to protocol 'Animal' is not supported
Fail<Plants>.self // OK, @objc protocol can concrete type conforming.
```

The architecture of DelegateProxy is based on the behavior of NSObject, Objective-C. 
If use Delegate(not NSObject) in DelegateProxy, there are no way to make work well some of methods like `forwardDelegate`, `sentMessage`, `methodInvoked`. If don't use these feature, I think it doesn't need to use DelegateProxy.
NSObject(NSObjectProtocol) is part of Objective-C, not pure swift. I think that's make sense add `@objc` keyword if need.

@kzaher 
If we remove every conditional from DelegateProxy.Delegate, we can support any Delegate(without `@objc`), but if Delegate is not NSObject, then `forwardDelegate`, `sentMessage`, `methodInvoked` does not work. And DelegateProxy code will get many type casting again 😢 
In my opinion, it make confusing, the Delegate(not NSObject) make not work some of features like `forwardDelegate`, `sentMessage`, `methodInvoked`. 
So I suggest revert #1442, and if we want to solve this issue, it's better that add one more feature for pure swift. (I'm not sure what should we support on pure swift, but I think it will not be Proxy.)

**Comment by mobilinked** [comment] 2017-10-20 04:27
BTW, 
- Before RxSwift/RxCocoa 4.0.0, we use the similar solution to support pure swift delegate
- I did think that adding @objc to pure swift protocol makes the code be much dirty (personal opinion) 

Is it possible to get the old method back to support pure swift code (maybe using another class name)? or we have to change our UI lib directly to add Rx subject in the UI class.

**Comment by kzaher** [comment] 2017-10-20 08:52
I believe this is a problem with Swift compiler. I've reported a bug
https://bugs.swift.org/browse/SR-6173

**Comment by kzaher** [comment] 2017-10-21 13:35
Ok, we will create a workaround for this. Please follow #1442 since this is a dupe.

**Closed by kzaher** 2017-10-21 13:35 UTC

**Comment by jaysonjh** [comment] 2018-08-21 14:15
@mobilinked I also has this issue:
"super.init" cannot be called outside of an initializer

How to fix it?
