### ISSUE TITLE
Xcode 11.4 and swift 5.2

### ISSUE THREAD

**Issue by bukira** [ReactiveX/RxSwift#2154] opened 2020-03-25 10:34 UTC
**Short description of the issue**:
doesn't compilee with Carthage

**Expected outcome**:
compiles

**What actually happens**:
doesn't compile

**RxSwift/RxCocoa

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [x] watchOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:
11.4

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] Carthage

**Comment by freak4pc** [comment] 2020-03-25 10:37
This is a duplicate of #2125. We can continue the discussion there. Thanks for reporting.

**Closed by freak4pc** 2020-03-25 10:37 UTC
