### ISSUE TITLE
Read-only version of Variable type

### ISSUE THREAD

**Issue by damienrambout** [ReactiveX/RxSwift#1236] opened 2017-05-03 16:03 UTC
**Short description of the issue**:

I'd like to be able to share a `Variable` object, without allowing access to the setter of `value`.

**Expected outcome**:

Basically, it could be another type (e.g. `ReadOnlyVariable<E>`) based on an underlying `Variable`, exposing a read-only `value` property, and a `asObservable()` function.
So:
- I want external objects to have a direct access to a value (through `value`), and/or updates of this value (through `asObservable()`). 
- I don't want these external objects to be able to update this value.

**What actually happens**:

I must either share a `Variable` with other objects, risking this variable to be externally modified by letting these other objects update the `value` property. Or I can share a `BehaviorSubject`, which gives access to `onNext(...)` to update it's internal value.

Am I missing something that already exists in RxSwift and could solve my problem?

**Self contained code example that reproduces the issue**:

Here's what I did on my side
```swift
public final class ReadOnlyVariable<Element> {
    public typealias E = Element
    
    private let variable: Variable<Element>
    
    public convenience init(_ value: Element) {
        self.init(Variable(value))
    }
    
    public init(_ variable: Variable<Element>) {
        self.variable = variable
    }
    
    public var value: E {
        return variable.value
    }
    
    public func asObservable() -> Observable<E> {
        return variable.asObservable()
    }
}

public extension Variable {
    public func asReadOnly() -> ReadOnlyVariable<E> {
        return ReadOnlyVariable(self)
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.4.1

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment] 2017-05-05 17:50
Hi @damienrambout ,

I think this is a dupe of 
https://github.com/ReactiveX/RxSwift/pull/1118
https://github.com/ReactiveX/RxSwift/pull/697

The bottom line is:
* It's convenience one can easily add if needed, no private API is needed
* It's useful for a limited number of use cases in a specific architectures, and this library is agnostic with respect to architectures
* It is conceptually pointed in the direction opposite to declarative programming
* For it to be really useful one needs to not only add this, but another imperative set operators that transform it, which we aren't going to do anyway

¯\\\_(ツ)\_/¯ 

Remedies:
* use `Observable` sequence or `Driver`
* use `withLatestFrom` operator if you want to read latest `Observable/Driver` state on some event
* use some other architecture where you don't need to do this (take a look at `system` operator and `RxFeedback`)
* create a private extension in your project if you really want to do this

**Closed** 2017-05-09 18:40 UTC

**Comment by damienrambout** [comment] 2017-05-10 08:45
Hi @kzaher,

Thank you for the great explanation! I agree with you on all points. 
You are right about using this only in specific architectures such as MVP or MVVM.
I guess I'll be trying https://github.com/inamiy/RxProperty, see if it fits my needs.

Sorry of the duplicate by the way.

Cheers,
Damien
