### ISSUE TITLE
Request: switchIfEmpty and defaultIfEmpty operators

### ISSUE THREAD

**Issue by NitroNbg** [ReactiveX/RxSwift#1000] opened 2016-11-15 09:20 UTC
*Short description of missing functionality*:

These operators are present in other ReactiveX implementations. The switchIfEmpty operator attaches the same observer that was bound to the observable the method is called on, and runs it if the original observable didn't emit any items. The defaultIfEmpty operator emits a default (sentinel) value in case the observable it is called completes without emiting anything.

*Short code example of how you would like to use the API*:

`observableForCachedItems.switchIfEmpty(observableForOnlineItems).subscribe(...)`
`observableForDateRegistered.defaultIfEmpty(NSDate())`

*The reason why I need this functionality*:

We implemented these two operators on our own at my company when we were developing Android and iOS apps that were targeting one REST endpoint and had another one as a fallback in case we receive empty JSON response from the first one. The defaultIfEmpty operator is handy for displaying sentinel values ("Empty search results") to the user.

*Code I have right now*:

I have the implementation for these two operators ready. We wrote them as Swift extensions for `ObservableType` and I would open a pull request, but I've never contributed before and I'm not sure about your coding guidelines and requirements. If you want I can attach the code for these two operators that I wrote when I needed to use them.

**Comment by kzaher** [comment] 2016-11-16 22:40
Hi @NitroNbg ,

this is dupe of #662, let's continue discussion there.

**Closed by kzaher** 2016-11-16 22:40 UTC
