### ISSUE TITLE
Maybe delegate was already set in `xib` or `storyboard` and now it's being overwritten in code.

### ISSUE THREAD

**Issue by wangmengling** [ReactiveX/RxSwift#675] opened 2016-05-11 04:00 UTC
ShareTableViewController: 0x7feda58d6330>)` for object -> `<UITableView: 0x7feda5136000; frame = (0 0; 375 667); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x7feda5a0a790>; layer = <CALayer: 0x7feda5a007e0>; contentOffset: {0, 0}; contentSize: {375, 307}>`.
Maybe delegate was already set in `xib` or `storyboard` and now it's being overwritten in code.: file /Users/apple/Documents/luoye/lawyeruser/newLuoye/Pods/RxCocoa/RxCocoa/Common/DelegateProxyType.swift, line 199

**Comment by alexandremorgado** [comment] 2016-05-11 12:27
Same problem here after upgrades to Cocoapods 1.0.0 and Xcode 7.3.1.

**Comment by sergdort** [comment] 2016-05-11 13:23
Hi, guys!

I don't think it a problem of Cocoapods

Most likely you are using `bindTo(tableView. rx_itemsWithCellIdentifier)` or methods from that family

What it [does](https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/iOS/UITableView%2BRx.swift#L48) is trying to create data source and subscribe to `subscribeProxyDataSourceForObject`

You just need to remove it from xib or `tableView.dataSource = nil` before calling `bindTo` or use `rx_setDataSource`

**Comment by alexandremorgado** [comment] 2016-05-11 13:59
@sergdort, you're right. It works setting datasource and delegate with nil in my viewDidLoad! But I still don't understand why this problem start occurring just after mentioned upgrades...   

Thanks!

**Comment by kzaher** [comment] 2016-05-11 19:24
Hi guys,

This is an assert that fires when you have a previous data source set to warn you that you might be breaking that previous set data source.

```
assert(proxy.forwardToDelegate() === nil, "There is already a delegate set -> `\(proxy.forwardToDelegate()!)` for object -> `\(object)`.\nMaybe delegate was already set in `xib` or `storyboard` and now it's being overwritten in code.")
```

I'm kind of confused how to resolve this issue? This behavior is by design.

**Comment by sergdort** [comment] 2016-05-11 19:52
Hi, @kzaher . It seems to me that a lot of  people don't understand what is the problem within assert message . I saw some people asked the same question in the slack channel.

May be we could somehow  improve the message so it would be, more understandable. To kind of explaine why this a problem, because as far as I remember even if you creat `UITableviewController` manually, the `dataSource` and `delegate` set to the instance of controller, so it not only xib or storyboard.

**Comment by kzaher** [comment] 2016-05-11 20:05
How about this?

assert(proxy.forwardToDelegate() === nil, "This is a feature to warn you that there is already a delegate (or data source) set somewhere previously. The action you are trying to perform will clear that delegate (data source) and that means that some of your features that depend on that delegate (data source) being set will likely stop working.\nIf you are ok with this, try to set delegate (data source) to `nil` in front of this operation.\n This is the source object value: `\(object)`\n This this the original delegate (data source) value: `\(proxy.forwardToDelegate()!)`\nMaybe delegate was already set in `xib` or `storyboard` and now it's being overwritten in code.\n")

**Comment by kzaher** [comment] 2016-05-15 18:50
This is just released. I think we can close it now.

**Closed by kzaher** 2016-05-15 18:50 UTC

**Comment by Bashta** [comment] 2016-12-27 04:59
What if i still need access to `tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat` but i have set the delegates to nil so they are not being called.

**Comment by kzaher** [comment] 2016-12-27 13:28
@Bashta you would just use `rx.setDelegate`:

```
tableView.delegate = nil
tableView.rx.setDelegate(yourDelegate).addDisposableTo(disposeBag)
```

**Comment by Bala-iOS** [comment] 2017-05-09 08:03
Am using latest version of `rxSwift` and `rxDataSource` ... I too face the same problem ... And I use `tableView.dataSource` = nil and `tableView.dataSource = nil` before `bindTo` or use `rx_setDataSource`. Anybody help me to fix this.

**Comment by ZZHHAANNGG** [comment] 2018-08-08 03:13
I have a similar issue, the TableView has no data source before binging.

Assertion failed: This is a feature to warn you that there is already a delegate (or data source) set somewhere previously. The action you are trying to perform will clear that delegate (data source) and that means that some of your features that depend on that delegate (data source) being set will likely stop working.
If you are ok with this, try to set delegate (data source) to `nil` in front of this operation.
 This is the source object value: <UITableView: 0x7fdde9886e00; frame = (0 199; 414 537); clip

```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.tableView.tableFooterView = UIView(frame: CGRect.zero)
        
        self.startDatePickerView = UIDatePicker(frame: CGRect(x: 0, y: 0, width: self.view.frame.size.width, height: 216))
        self.startDatePickerView.datePickerMode = .date
        self.startDatePickerView.date = Calendar.current.date(byAdding: .month, value: -1, to: Date()) ?? Date()
        
        self.endDatePickerView = UIDatePicker(frame: CGRect(x: 0, y: 0, width: self.view.frame.size.width, height: 216))
        self.endDatePickerView.datePickerMode = .date
        
        self.startDateTextField.inputView = startDatePickerView
        self.endDateTextField.inputView = endDatePickerView
    
        self.viewModel = CustomerViewModel()
        
        (self.startDateTextField.rx.text <-> self.viewModel.startDateTime).disposed(by: rx.disposeBag)
        (self.endDateTextField.rx.text <-> self.viewModel.endDateTime).disposed(by: rx.disposeBag)
        
        self.viewModel.list.subscribe(onNext:{ [unowned self](event) in
            switch event {
            case .success(let response):
                
                response.drive(self.tableView.rx.items(cellIdentifier: "customerCell", cellType: UITableViewCell.self))
                    {data source) to `nil` in front of this operation.
                        (index, customer, cell) in
                        cell.textLabel?.text = "\(customer.UserName ?? "")\t\t\(customer.CreateTime ?? "")"
                    }
                    .disposed(by: self.rx.disposeBag)
            case .failure(let error):
                print( error )
            }

        }).disposed(by: rx.disposeBag)

    
        
        
        self.startDatePickerView.rx.date.map{ [weak self](date) in
            return self?.viewModel.dateFormater.string(from: date)
        }.bind(to: self.startDateTextField.rx.text).disposed(by: rx.disposeBag)
        
        self.endDatePickerView.rx.date.map{ [weak self](date) in
            return self?.viewModel.dateFormater.string(from: date)
            }.bind(to: self.endDateTextField.rx.text).disposed(by: rx.disposeBag)
    }
}
```

**Comment by freak4pc** [comment] 2018-08-08 11:38
@ZZHHAANNGG Make sure the Table View doesn't have a delegate as well, not just a datasource attached.

**Comment by ZZHHAANNGG** [comment] 2018-08-08 12:02
@freak4pc  I am sure the TableView has no delegate and datasouce. I changed the `unowned self` to `weak self` and the cell will not be created, the table is blank and has no such assertion issue.

**Comment by ivolnov** [comment] 2018-08-29 05:57
Got to be some weird storyboard magic or UITableViewController defaults - using itself as a datasource and a delegate...

**Comment by RazeeHJ** [comment] 2018-10-01 21:40
How can I set it before bind(to:). As it’s binding an observable, whenever the observable has the data it will load.

I’ve a view model that has the observables once there is data it will bind(to:tableView.rx.items...) and if there is no data I set tableview.delegate = self and load a shimmering view but this causes a problem when the data has been loaded and wants to bind to table view

**Comment by dylan** [comment] 2018-10-04 18:27
I've ran into this same issue, I too believe it's a storyboard thing. I've just set ```tableView.dataSource = nil``` and moved on.

**Comment by ivolnov** [comment] 2018-10-05 06:15
As far as I understand you can just use a raw UIViewController or etc and dragndrop a tableview into it, which is different from using a UITableViewController which conveniently implements delegates and binds itself to the table for free. In the latter case you will need to explicitly set delegates to nil before using the Rx fun...

**Comment by freak4pc** [comment] 2018-10-05 07:35
UITableViewController takes over the dataSource in a way that can't be disconnected (AFAIK) via Storyboard - so in that case you'll need to manually set the dataSource to `nil`. Option 2 which is what I do, is just use a UITableView in a UIViewController - much finer control.

**Comment by marcopax** [comment] 2018-11-13 14:00
I had a similar crash. Long story short: I resolved performing the cleaning before setting the delegate:

```
collectionView.dataSource = nil
collectionView.delegate = nil

collectionView.rx
    .setDelegate(self)
    .disposed(by: disposeBag)
```

Or in a `do` block before binding:

```
myDriver
            .do {
                self.tableView.dataSource = nil
                self.tableView.delegate = nil
            }
            .drive(tableView.rx.items(dataSource: self.dataSource))
            .disposed(by: disposeBag)
```

No crashes anymore.

**Comment by Ualikhan07** [comment] 2019-05-16 11:47
> @Bashta you would just use `rx.setDelegate`:
>  
> ```
> tableView.delegate = nil
> tableView.rx.setDelegate(yourDelegate).addDisposableTo(disposeBag)
> ```

which delegate u set? i add programmatically tableView and now i can't set delegate...

**Comment by Bashta** [comment] 2019-05-29 20:15
> > @Bashta you would just use `rx.setDelegate`:
> > ```
> > tableView.delegate = nil
> > tableView.rx.setDelegate(yourDelegate).addDisposableTo(disposeBag)
> > ```
> 
> which delegate u set? i add programmatically tableView and now i can't set delegate...

Thanks, man but the question was from Dec 27, 2016 XD
