### ISSUE TITLE
Error on rx_modelSelected(), even though rx_itemsWithCellIdentifier() used

### ISSUE THREAD

**Issue by coryoso** [ReactiveX/RxSwift#294] opened 2015-11-27 10:05 UTC
`tableView.rx_modelSelected()` crashes with `This method only works in case one of the rx_items* methods was used.` message, even though `rx_itemsWithCellIdentifier()` is used.

Complete code of the table view controller is below. Bug or am I doing something wrong?

    let disposeBag = DisposeBag()
    var models: Driver<[String]>?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView.registerClass(UITableViewCell.self, forCellReuseIdentifier: "TextCell")
        
        models = Variable(["Value"])
            .asDriver(onErrorJustReturn: ["Value"])
        
        models!
            .drive(tableView.rx_itemsWithCellIdentifier("TextCell")) { (_, value, cell: UITableViewCell) in
                cell.textLabel?.text = value
            }
            .addDisposableTo(disposeBag)
        
        tableView.rx_modelSelected()
            .asDriver()
            .driveNext { value in
                print(value)
            }
            .addDisposableTo(disposeBag)
    }

**Comment by kzaher** [comment] 2015-11-27 10:13
Hi @coryoso ,

are you using the latest beta.3 version? I believe that was broken in one of the previous versions, but should be fixed in latest version. Can you please tell me which version are you using?

**Comment by coryoso** [comment] 2015-11-27 10:25
Hmm, my cartfile contains `github "ReactiveX/RxSwift" "2.0.0-beta.3"`, so i'm using beta.3

**Comment by kzaher** [comment] 2015-11-27 21:24
Hi @coryoso ,

this one was a surprise for me also. We need to make that API better :) 

I don't think this is a bug, it's just a misfortunate result :)

Let me know does this work ...

```
tableView.rx_modelSelected()
        .asDriver()
        .driveNext { (value: String) in
            print(value)
        }
        .addDisposableTo(disposeBag)
```

The problem is that according to this code

```
tableView.rx_modelSelected()
        .asDriver()
        .driveNext { value in
            print(value)
        }
        .addDisposableTo(disposeBag)
```

... because of using print statement compiler assumes that value is typed `Any` instead of `String`.

That's what's causing that nasty error message.

Can you please confirm this works for you?

I think we would change that interface in future, so we would require user to write:

```
tableView.rx_modelSelected(String.self)
        .asDriver()
        .driveNext { value in
            print(value)
        }
        .addDisposableTo(disposeBag)
```

... so these kinds of accidents don't happen again.

**Comment by coryoso** [comment] 2015-11-28 12:04
Specifing the type of value does fix the issue! 
Changing the `rx_modelSeclected` method to include the type sounds like a good idea, especially for newcomers

**Comment by kzaher** [comment] 2015-11-29 21:19
I think I'll be shipping that required type tomorrow in beta.4 :)

Thnx for reporting. It's hard to anticipate all of these interactions between compiler, environment and people's code, although, this one could have been foreseen :)

Oh well, we'll make this better soon :)

**Comment by kzaher** [comment] 2015-12-07 00:27
Improved version of `rx_modelSelected` has just been released together with simple examples. Closing this for now :)

**Closed by kzaher** 2015-12-07 00:27 UTC
