### ISSUE TITLE
Custom UIControl

### ISSUE THREAD

**Issue by Z-JaDe** [ReactiveX/RxSwift#939] opened 2016-10-13 09:46 UTC
Custom UIControl subclass(JDSegmentedControl), cannot use (static func value (: :)) method, because of his authority is not public

**Comment by kzaher** [comment] 2016-10-15 10:18
Hi  @Z-JaDe ,

I think this is a dupe of #681.

**Comment by Z-JaDe** [comment] 2016-10-15 12:33
Thanks @kzaher,
when I use KVO，"func observe<E: KVORepresentable>(_ type: E.Type, _ keyPath: String, options: NSKeyValueObservingOptions = [.new, .initial], retainSelf: Bool = true) -> Observable<E?>"
if the options is [.old],  I didn't see you implement it.
I see only like this,
"-(void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context {
    @synchronized(self) {
        self.callback(change[NSKeyValueChangeNewKey]);
    }
}"

**Closed** 2016-10-18 16:30 UTC
