### ISSUE TITLE
RxTest referencing to invalid libswiftXCTest.dylib

### ISSUE THREAD

**Issue by gringoireDM** [ReactiveX/RxSwift#2072] opened 2019-09-25 16:53 UTC
Hello everyone, I was wondering if someone here had my same issue.

I have an iOS project in which there are multiple modules. each module has its own test bundle.
Tests run perfectly until I install via cocoa pods RxTest.

After install, test bundles crash with the following message in console:

> 2019-09-25 17:46:29.756701+0100 xctest[70947:11876875] The bundle “MyModuleTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2019-09-25 17:46:29.756838+0100 xctest[70947:11876875] (dlopen_preflight(/Users/.../Library/Developer/Xcode/DerivedData/.../Products/Debug-Dev-iphonesimulator/MyModuleTests.xctest/MyModuleTests): Library not loaded: /usr/lib/swift/libswiftXCTest.dylib
  Referenced from: /Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-Dev-iphonesimulator/MyModuleTests.xctest/MyModuleTests/RxTest.framework/RxTest
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftXCTest.dylib: mach-o, but not built for iOS simulator)
Program ended with exit code: 9

I checked already the usual suspects: The run path searchPath is `$(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'`as it should be.

I tried for quite a lot of time to get this to work playing with build configurations, but all without any success. If I remove RxTest, everything goes back to normal and tests start running again.

Suggestions?

**Comment by muehlemann** [comment] 2019-09-26 14:09
I am also experiencing this issue. RxTest seems to break my test bundle after updating to Xcode 11.0

**Comment by gringoireDM** [comment] 2019-09-27 11:14
@muehlemann did you solve this somehow?

**Comment by muehlemann** [comment] 2019-09-27 12:09
No, I had to downgrade to Xcode 10.3 to be able and continue development.

**Comment by schroepf** [comment] 2019-09-30 11:44
I noticed the same issue. But it seems that I can run the tests from XCode 11 on the iOS 13 simulator. But when I try to run them on a simulator with an older iOS version (in my case iOS 11.4) I see that exact same errors as you do

**Comment by muehlemann** [comment] 2019-09-30 11:56
@schroepf Same for me. Tests run on iOS 13 simulator, but fail on everything older than that.

**Comment by freak4pc** [comment] 2019-10-03 16:28
Can anyone confirm this on the latest Xcode 11.2 beta?

**Comment by freddi-kit** [comment] 2019-10-08 08:33
@freak4pc 

This crash also occurred on Xcode 11.2 beta.
FYI: There is a related reported issue on CocoaPods https://github.com/CocoaPods/CocoaPods/issues/9165

**Comment by gringoireDM** [comment] 2019-10-15 17:57
just tried with the latest public Xcode. same result.

**Comment by gringoireDM** [comment] 2019-10-15 18:03
anyway, in my case any simulator won't run the tests. no idea why.

**Comment by gringoireDM** [comment] 2019-10-15 18:24
Correction. just pre iOS 13 simulators have this issue. just like previously reported

**Comment by artyom-razinov** [comment] 2019-10-16 18:21
I solved the same issue in my project by switching everything to Swift 5 and adding a line of code in the podspec that requires XCTest.

Before:
```
  s.frameworks = 'XCTest', 'XCTAutomationSupport'
  
  s.xcconfig = {
    'LD_RUNPATH_SEARCH_PATHS' => '$(inherited) "$(PLATFORM_DIR)/Developer/Library/Frameworks" "$(PLATFORM_DIR)/Developer/Library/PrivateFrameworks"',
    'FRAMEWORK_SEARCH_PATHS' => '$(inherited) "$(PLATFORM_DIR)/Developer/Library/Frameworks" "$(PLATFORM_DIR)/Developer/Library/PrivateFrameworks"'
  }
```

After:
```
  s.frameworks = 'XCTest', 'XCTAutomationSupport'
  
  s.xcconfig = {
    'LIBRARY_SEARCH_PATHS' => '$(TOOLCHAIN_DIR)/usr/lib/swift-$(SWIFT_VERSION)/$(PLATFORM_NAME) $(inherited)',
    'LD_RUNPATH_SEARCH_PATHS' => '$(inherited) "$(PLATFORM_DIR)/Developer/Library/Frameworks" "$(PLATFORM_DIR)/Developer/Library/PrivateFrameworks"',
    'FRAMEWORK_SEARCH_PATHS' => '$(inherited) "$(PLATFORM_DIR)/Developer/Library/Frameworks" "$(PLATFORM_DIR)/Developer/Library/PrivateFrameworks"'
  }
```

I hope this can help.

**Comment by gringoireDM** [comment] 2019-10-16 22:12
I checked Quick and Nimble Podspec and they actually do have `LIBRARY_SEARCH_PATHS`. No problem with those. @freak4pc can we add this to the podspec? What do you think? I can open a PR myself and check if it works if you are busy.

**Comment by freak4pc** [comment] 2019-10-17 07:09
Let me run a few tests first and I’ll take care of it if everything looks good.

Thanks,

Shai.

**Comment by gringoireDM** [comment] 2019-10-17 11:22
Thank you @freak4pc , please let me know if you need at any point any help.

**Comment by freak4pc** [comment] 2019-10-21 15:52
@gringoireDM I've checked both Quick and Nimble and can't find it being used. Where did you see it? 

https://github.com/Quick/Nimble/search?q=LIBRARY_SEARCH_PATHS&unscoped_q=LIBRARY_SEARCH_PATHS

**Comment by freak4pc** [comment] 2019-10-21 15:58
Perhaps you're referring to FRAMEWORK_SEARCH_PATHS ?

**Comment by gringoireDM** [comment] 2019-10-21 16:29
I don't really know what makes that podspec special. I see Quick running with no issues at all on xcode11 any simulator, while RxTest doesn't on simulators < iOS 13

**Comment by freak4pc** [comment] 2019-10-21 16:29
I’ll run a few tests tomorrow morning and post updates here :)

Shai.

**Comment by freak4pc** [comment] 2019-10-21 17:40
I can't seem to reproduce the issue you're having. 

I'm on Xcode 11 with the following test with RxTest and RxBlocking installed via CocoaPods: 

![image](https://user-images.githubusercontent.com/605076/67228978-0aa3bd80-f443-11e9-931a-9abe283e5fe1.png)

I tried with iOS 11.4 and 13 deployment targets and have no issues.

Can anyone provide a reproducible project here please?

**Comment by freak4pc** [comment] 2019-10-22 07:51
Forgot to tag people who had issues @gringoireDM @muehlemann @freddi-kit @schroepf @artyom-razinov

**Comment by gringoireDM** [comment] 2019-10-28 16:19
@freak4pc I tried to reproduce it on a clean project and I couldn't. After more investigation I came to the conclusion that the problem was in the specific project on which I was having the issue. It's a new codebase for me, so I didn't know that we had custom xcconfig files. The problem was with those + cocoa pods ones conflicting.

Thank you so much for your time. 
For me we can close this issue.

**Comment by muehlemann** [comment] 2019-10-28 20:58
@freak4pc Cant reproduce in a clean project either. 

@gringoireDM Any pointers on the conflicting areas? I'm working on a project that uses custom xcconfig files as well but have not been able to figure out the issue yet.

**Comment by freak4pc** [comment] 2019-10-28 20:59
Thanks. Closing this for now.

**Closed by freak4pc** 2019-10-28 20:59 UTC

**Comment by gringoireDM** [comment] 2019-10-30 12:39
@muehlemann I just removed the xcconfig files and add the custom configurations as user defined build configs directly to the project (which is equivalent if you have just one project).

**Comment by schroepf** [comment] 2019-11-06 06:34
hi @freak4pc in my project we also use custom xcconfig files and it will be really hard and a massive effort to get rid of them... is there any other known workaround for this issue? or will there be a RxSwift update which fixes that issue?
Do we already know the root cause why this only happens for RxTest and no other pods?

**Comment by freak4pc** [comment] 2019-11-06 06:38
Given the xcconfig files are the only difference, this doesn’t seem to be an issue with RxSwift itself so we probably won’t spend time investigating it.

**Comment by schroepf** [comment] 2019-11-06 06:46
oh... ok... :)

I checked the RxTest.podspec and it contains:
```
s.pod_target_xcconfig = { 'ENABLE_BITCODE' => 'NO' }
```
which might be what's causing that issues... do you know if that's critical for RxTest to work correctly? According to cocoapods' issue tracker that shouldn't be necessary: https://github.com/CocoaPods/CocoaPods/issues/3936

**Comment by muehlemann** [comment] 2019-11-12 13:58
I finally found a solution for this issue. Turns out that it's an Apple bug. Anybody thats looking for a fix should reference this gist: https://gist.github.com/liamnichols/3507faf70ecca201cb4300645caa9b74

Just swap out your simulator version and you should be good to go.

**Comment by AlexShubin** [comment] 2019-12-02 14:13
Hi! 

'$(TOOLCHAIN_DIR)/usr/lib/swift-$(SWIFT_VERSION)/$(PLATFORM_NAME)' worked for me only in combination with `DEAD_CODE_STRIPPING = YES;` on XCode 11.2.1.

Hope it helps!

**Comment by verebes1** [comment] 2020-10-10 13:50
> $(inherited) '@executable_path/Frameworks'

For me, it helped when I went into the Build Settings and pasted $(inherited) '@executable_path/Frameworks'
into User Header Search Paths and then restart Xcode.
![Screenshot 2020-10-10 at 14 49 44](https://user-images.githubusercontent.com/22076146/95656696-f18a9580-0b07-11eb-807a-44da21e7451a.png)

**Comment by ralbertini** [comment] 2021-04-11 06:00
I am using XCode 12.4

I tried everything above, but when I changed from app to test target, the problem finish.


![Screen Shot 2021-04-11 at 02 57 25](https://user-images.githubusercontent.com/43758752/114294046-cd395280-9a71-11eb-867e-57fb2892dd50.png)

**Comment by JuancarlosExperis** [comment] 2022-03-04 11:27
I had the same issue with my own module, adding the following configuration to my module.podspec works for me 

 s.pod_target_xcconfig = {
      'ENABLE_TESTING_SEARCH_PATHS' => 'YES',
      'OTHER_LDFLAGS' => '$(inherited) -weak-lXCTestSwiftSupport -Xlinker -no_application_extension',
    }
