### ISSUE TITLE
Crash on runtime if SPM is used

### ISSUE THREAD

**Issue by RolandasRazma** [ReactiveX/RxSwift#2094] opened 2019-10-27 09:07 UTC
If I use SPM for Rx* it fails to create `ReplaySubject` on runtime with `EXC_BAD_ACCESS`. It does work if I use CocoPods

```swift
import UIKit
import RxSwift

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    
    private let modelSubject = ReplaySubject<Bool>.create(bufferSize: 1)
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        return true
    }
    
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift 5.0.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
11.2 beta (11B41)
```

**Installation method**:
  - [x] SPM
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

<img width="549" alt="Screenshot 2019-10-27 at 09 03 08" src="https://user-images.githubusercontent.com/1027187/67632241-0808f400-f899-11e9-892b-9a380ea8ccad.png">

<img width="307" alt="Screenshot 2019-10-27 at 09 03 00" src="https://user-images.githubusercontent.com/1027187/67632244-0ccda800-f899-11e9-9f63-0fae6f0f2388.png">

![Screenshot 2019-10-27 at 09 04 10](https://user-images.githubusercontent.com/1027187/67632246-0f300200-f899-11e9-93c9-8abf80be7c4d.png)

**Comment by y8k** [comment] 2019-10-30 08:10
I have same problem...

**Comment by thomas3687** [comment] 2019-11-01 10:52
Same problem with the official Xcode 11.2 (11B52)

**Comment by robcas3** [comment] 2019-11-01 12:30
Same thing here with Xcode 11.2 (11B52).  I've downgraded to Xcode 11.1 and it works.
I hope Apple fix this huge problem.

**Comment by tcldr** [comment] 2019-11-01 13:06
This is caused by SR-11564. (https://bugs.swift.org/browse/SR-11564)

**Comment by RamblinWreck77** [comment] 2019-11-01 15:33
This is absolutely wild. I can't believe Apple shipped Xcode with a bug this bad.

**Comment by freak4pc** [comment] 2019-11-01 15:34
Meh. I'm not sure if there's any point in keeping this open as it's not an issue with RxSwift itself as a library. Thoughts?

**Comment by tcldr** [comment] 2019-11-01 15:37
@freak4pc personally, I’d leave it open to prevent too many dupes. Anyone using SPM will be hitting this and likely checking the issues page here.

**Comment by RamblinWreck77** [comment] 2019-11-01 15:38
@freak4pc I see where you're coming from, but at least in my case RxSwift was crashing "first" (bad access on ReplaySubject.create) so I came here. This issue was at least useful to me to link me in to the broader issue in SR-11564 so it might help others.

**Comment by freak4pc** [comment] 2019-11-01 15:38
They would still find this issue in search, but sure, let's leave it open for a couple more days.

**Comment by RamblinWreck77** [comment] 2019-11-01 15:48
Yeah this is 5 alarm fire bad, I agree with leaving it up for a few days. I'm sure someone's having a lovely Friday in Cupertino right about now. 🙃

**Comment by tcldr** [comment] 2019-11-01 22:31
Setting DEAD_CODE_STRIPPING=No in your Xcode build settings should workaround this for now. (Probably best to remember to switch it back on again once SR-11564 is fixed.) 

https://bugs.swift.org/browse/SR-11564?focusedCommentId=51285&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-51285

**Comment by freak4pc** [comment] 2020-01-05 18:51
Closing. Thanks for the investigation and workaround, @tcldr !

**Closed by freak4pc** 2020-01-05 18:51 UTC
