### ISSUE TITLE
Structured Concurrency support

### ISSUE THREAD

**Issue by isaac-weisberg** [ReactiveX/RxSwift#2331] opened 2021-06-16 09:37 UTC
Theoretically it could be possible to create an asynchronous scheduler that utilizes new Swift 5.5 structured concurrency features to schedule the observation/subscription to an observable as a part of a separate Task!

What does the maintenance team think about it?

**Comment by freak4pc** [comment] 2021-07-22 21:23
Not sure why you opened another issues, this seems like a dupe of #2342 (or the other way around). Closing.

**Closed by freak4pc** 2021-07-22 21:23 UTC
