### ISSUE TITLE
use cocoapod

### ISSUE THREAD

**Issue by hatjs880328** [ReactiveX/RxSwift#584] opened 2016-03-29 09:26 UTC
Module file was created by an older version of the complier;rebuild 'RxSwift' and try again :.............../X86_64.swiftmodule

**Comment by hatjs880328** [comment] 2016-03-29 09:26
Xcode version is 7.3

**Comment by bontoJR** [comment] 2016-03-29 09:31
Hello @hatjs880328, can you please try to clean the build folder or even delete the derived data and try to build again?

If it doesn't work, can you give more details about this error, such as:
- Toolchain used in Xcode (you can see it under `Xcode -> Toolchains`
- Cocoapods' version
- More details about the Podfile
- Example of the code importing the `RxSwift` module

With all these information I think I can try to reproduce the error.

**Comment by hatjs880328** [comment] 2016-03-29 09:36
pods version is 0.39.0


podfile like :+1: 

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SnapKit', '~> 0.19.1'

pod 'Alamofire', '~> 3.1.5'

pod 'RxSwift', '~> 2.3.1'

pod 'RxCocoa',   '~> 2.3.1'

    pod 'RxBlocking', '~> 2.3.1'

    pod 'RxTests',    '~> 2.3.1'

**Comment by hatjs880328** [comment] 2016-03-29 09:43
set Bitcode enabled 
show : 
cannot load module 'rxswift' as 'rxswift'

**Comment by hatjs880328** [comment] 2016-03-29 09:52
ld: '/Applications/xcode7.3/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by bontoJR** [comment] 2016-03-29 12:36
It sounds like a very strange problem considering that since 7.1 I never saw it anymore, I can't reproduce the problem, maybe @orta or @neonichu might have an idea how to solve this?

**Comment by neonichu** [comment] 2016-03-29 12:39
Haven't seen this ever so  ¯\\\_(ツ)\_/¯

**Comment by hatjs880328** [comment] 2016-03-30 00:58
@neonichu
@orta

**Comment by kzaher** [comment] 2016-03-30 21:12
Hi @hatjs880328,

according to 
```
ld: '/Applications/xcode7.3/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```

and `Podfile`, I would say that you are trying to include `RxTests` in non test target, and that's causing an issue.

I would suggest using new `Cocoapods` target syntax for defining dependencies so you can limit that `RxTests` are applied only to unit tests target.

**Comment by tomburns** [comment] 2016-04-04 14:08
@kzaher As far as I can tell, this is an actual issue anytime you're building for device with RxTests in the project, as XCTest does not include bitcode. Can we just change the build flag in the Rx project to disable bitcode for the test utility components?

**Comment by kzaher** [comment] 2016-04-04 21:30
Hi @tomburns ,

I guess we could, but I'm little confused. Last time I've tried to run unit tests on device:

<img width="665" alt="screen shot 2016-04-04 at 23 29 19" src="https://cloud.githubusercontent.com/assets/1641148/14263825/2593e8e6-fabd-11e5-812d-0020333f79f1.png">

**Comment by kzaher** [comment] 2016-04-20 18:32
Anyway, I think we can close this one, unsure what to more here. I think this was caused by using RxTests in app binary.

We can open new issues if this pops up in future.

**Comment by tomburns** [comment] 2016-04-21 22:49
@kzaher FWIW this is still an issue; I've worked around it by adding a post-install hook to my pod file, but it would be much simpler to simply disable bitcode for the RxTests target and I don't see what the harm would be. You're correct that you can't run framework logic tests on device, however you *can* run unit tests injected into an application bundle on device, which is where I ran into this issue.

**Comment by tomburns** [comment] 2016-04-21 22:51
RxBlocking should be disabled as well if you decide to change them; as I understand it both are purely meant for use in test bundles, so this should be an acceptable change (until XCTest supports bitcode)

**Comment by kzaher** [comment] 2016-04-21 22:53
Hi @tomburns ,

I'm little confused, if you install using CocoaPods, it shouldn't make any difference if I turn bitcode on or off in project, right?

We are open to PRs. I'm not sure what action are you suggestion we should take. Bitcode is disabled for RxTests.

**Comment by kzaher** [comment] 2016-04-21 22:54
Is there any way of disabling bitcode in podspec?

**Comment by retsohuang** [comment] 2016-04-26 19:27
I think you can add this line of code in your pod spec.
```
s.pod_target_xcconfig = { 'ENABLE_BITCODE' => 'NO' }
```

**Comment by kzaher** [comment] 2016-05-15 14:57
Thnx @retsohuang ,

I'll include this in RxTests for 2.5 because XCTest doesn't have bitcode turned on, and we can see how that will go :)

**Comment by kzaher** [comment] 2016-05-15 18:50
Attempt #2 to close this issue. Feel free to reopen it if it's not working :)

**Closed by kzaher** 2016-05-15 18:50 UTC
