### ISSUE TITLE
Patch release blocker `duplicate symbol __TMRbBp` (https://bugs.swift.org/browse/SR-3081)

### ISSUE THREAD

**Issue by kzaher** [ReactiveX/RxSwift#970] opened 2016-10-30 22:49 UTC
We would like to release a patch for issues with RxCocoa on OSX, but we have ran into unexpected issues with Xcode 8.1

When running tests in `Release` or `Release-Tests` configuration we are getting  `duplicate symbol __TMRbBp`.

I'm curious about a few of things.

Does anyone have information when is patch for this coming out, or what's causing this?
Does anyone need an urgent patch release for RxCocoa?

**Comment by keith** [comment] 2016-10-31 02:28
For reference here's the Swift bug about this https://bugs.swift.org/browse/SR-3081

**Comment by keith** [comment] 2016-10-31 02:29
I haven't tried to compile this project to reproduce the issue here, but that ticket has a workaround at least for some cases.

**Comment by fe9lix** [comment] 2016-11-01 01:20
Hi! I've submitted a PR (#973) that should fix the issue with a workaround: Setting the build config "SWIFT_REFLECTION_METADATA_LEVEL" to "none" (-disable-reflection-metadata). According to the docs, the consequence is: 

"No reflection metadata is emitted into the binary. Accuracy of detecting memory issues involving Swift types in the Memory Graph Debugger will be degraded and reflection in Swift code may not be able to discover children of types, such as properties and enum cases. [-disable-reflection-metadata]"

Once the issue is fixed in the compiler, the setting could be set back to the default. I haven't found any use of reflection in the code base, so this should be acceptable as temporary workaround?

**Closed** 2016-11-02 08:15 UTC
Labels: help wanted

**Comment by keith** [comment] 2016-11-02 08:20
This has also been fixed on Swift master so hopefully will be out soon 😬
