### ISSUE TITLE
Cannot flatMap a Single trait to a Completable trait

### ISSUE THREAD

**Issue by programmerdave** [ReactiveX/RxSwift#1206] opened 2017-04-20 04:18 UTC
:warning: If you don't have something to report in the following format, it will probably be easier and faster to ask in the [slack channel](http://rxswift-slack.herokuapp.com/) first. :warning: 

:warning: Please take you time to fill in the fields below. If we aren't provided with this basic information about your issue we probably won't be able to help you and there won't be much we can do except to close the issue :( :warning:

*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

Cannot flatMap a ```Single``` trait to a ```Completable``` trait

**Expected outcome**:

I expect that the flatMap would let me convert to a Completable trait like in the example below.

**What actually happens**:

I get the following error:
```
 'flatMap' produces 'PrimitiveSequence<SingleTrait, R>', not the expected contextual result type 'PrimitiveSequence<SingleTrait, _>'
```

**Self contained code example that reproduces the issue**:

```
func convertExample() -> Completable {
    return Single<String>.create { single in
        single(.success("hello"))
        return Disposables.create()
      }
      .flatMap({ _ -> Completable in
        return Completable.empty()
      })
  }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

v3.4.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.3.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment] 2017-04-21 08:14
Hi @programmerdave ,

Yeah, you can't `flatMap` with completable by design. I'm not sure would it make sense to add that overload because of ambiguity, and if we started that road, we have quadratic problem on our hands. Flat map every trait with every other trait.

I understand why you would want this. Let's wait a while so I get a better feeling what are the common patterns with these new traits.

If it presents itself as something useful, we can add it later. I would rather add something little bit later, then add it easy, and then pull it out.

It would also be great if you could provide some context for this.

Hope it makes sense.

**Comment by programmerdave** [comment] 2017-04-21 21:09
@kzaher The main reason I would want to do this is because I have a lot of Single traits on methods that fetch data from the server and I would like in some cases at a higher level in an "interactor" class to chain a bunch of server calls and just know when it's completed so I can for example hide the loading UI. For now I've had to do this:

RxSwift+SingleToCompletable.swift
```
extension PrimitiveSequenceType where Self.TraitType == RxSwift.SingleTrait {
  func flatMapToCompletable() -> Completable {
    return Completable.create { completable -> Disposable in
      return self.subscribe(onSuccess: { _ in
        completable(.completed)
      }, onError: { error in
        completable(.error(error))
      })
    }
  }
}
```

In RxJava, which Single was modeled off of I think, there is a flatMap for this:
http://reactivex.io/RxJava/javadoc/io/reactivex/Single.html#flatMapCompletable(io.reactivex.functions.Function)

Single by itself works great until you get to a point where you don't care about the next value.

**Comment by programmerdave** [comment] 2017-05-02 00:56
I just realized this was a misunderstanding. I didn't really understand what Completable was doing. I'm going to go ahead and close this issue since you're right, I can't flatMap Completable. Thanks though!

**Comment by mono0926** [comment] 2017-05-02 04:41
@programmerdave 

Hello, I'm also troubled by [the reason you said](https://github.com/ReactiveX/RxSwift/issues/1206#issuecomment-296306220).

How did you handle this situation?

**Comment by kzaher** [comment] 2017-05-02 05:28
I've thought about this a bit, we can do something similar like RxJava did, it makes sense, but it might take a month or two to release it.

**Comment by vatrif** [comment] 2017-05-02 10:40
I also stumbled upon a similar issue: I have a bunch on Completable methods and I would like to chain them in a sane way. However, it seems that is not possible at the moment.

**Comment by hagmas** [comment] 2017-05-08 15:24
`Single` should be able to be converted into `Maybe` and `Completable`, and `Completable` only to `Maybe` (But Maybe cannot be converted to other traits). 

I wrote a code something like below and it's working. It takes out the source observable once by `asObservable` and then convert it to other traits.
```swift
extension PrimitiveSequence where TraitType == SingleTrait {
    public func asMaybe() -> PrimitiveSequence<MaybeTrait, Element> {
        return self.asObservable().asMaybe()
    }
    
    public func asCompletable() -> PrimitiveSequence<CompletableTrait, Never> {
        return self.asObservable().flatMap { _ in Observable<Never>.empty() }.asCompletable()
    }
}

extension PrimitiveSequence where TraitType == CompletableTrait, ElementType == Swift.Never {
    public func asMaybe() -> PrimitiveSequence<MaybeTrait, Element> {
        return self.asObservable().asMaybe()
    }
}
```

**Comment by naturalwarren** [comment] 2017-06-10 17:44
We have the same problem for flat mapping a Single to an Observable right?

**Comment by naturalwarren** [comment] 2017-06-13 15:17
Actually, you can just call `.asObservable` on the Single and then flatmap it to an Observable.

**Comment by dtartaglia** [comment] 2017-07-15 22:37
I'm struggling to understand `Completable`s and this issue has me even more confused... Given this:

	let chain = Observable<Void>.empty()
	let foo = chain.flatMap { () -> Observable<Int> in
		print("return 5")
		return Observable.just(5)
	}
	foo.subscribe { event in print(event) }

I would expect "return 5" to *not* get printed out because a completion event doesn't call flatMap's closure... but you are expecting it to get called when a Completable sends a completion event?

Why would you expect a Completable's complete event activate flatMap's closure when a normal observable's complete event doesn't?

**Comment by programmerdave** [comment] 2017-07-16 05:23
Exactly @dtartaglia, that's why I closed this issue a while back. A completable should rarely be used I believe because of this very reason. It makes it so much harder to use. Even in RxJava it's difficult to interchangeably use with other observables since Completables only complete and never call on next or other operators. I really hope @kzaher would just close this already. It's better to use Single or Maybe instead of this.

**Comment by minuscorp** [comment] 2017-07-19 16:16
What about, for example, network requests that yields just success or error? The `Completable` trait is the best representation of an operation that just completes or fails, although I recognize that the issue making `Completable`s able to be `flatMap` because of the main reason that they not produce any `next` event is understandable... Having network requests of Single<Void> really cringes me... I can't see a correct approach to this, if someone does I'll be grateful.

**Comment by programmerdave** [comment] 2017-07-19 16:38
@minuscorp In that case I would say by defaulting to a Completable, you're basically killing the reason you use Rx. You're breaking the chain and not allowing anything after it to continue the chain. I would say until someone comes up with an EmptySingle or something like that, you can just use Single<Void> but that's messy too. I do think there needs to be a better way to do this but Completable is not it.

**Comment by minuscorp** [comment] 2017-07-19 17:39
From now on, I've been thinking of this during the last weeks, and I'm rewriting my network layer using Single, it's easy just ignoring any next value when I don't want them but the ability of apply chain operations is critical.

Jorge Revuelta Herrero
Software Engineer
BISITE Research Group

**Comment by dtartaglia** [comment] 2017-07-19 17:41
@minuscorp Yes... Another way to solve the dilemma would be to materialize the Completable. Then the Event.completed would be wrapped in an Event.next.

**Comment by programmerdave** [comment] 2017-07-19 20:30
@dtartaglia I feel like that would cause even more confusion.... It technically is another concept than a completable.

**Comment by dtartaglia** [comment] 2017-07-19 20:53
@programmerdave However, it handles server errors nicely. `materialize` also wraps the Error into a normal next event so your pipe doesn't burst when the server emits an error. Very nice...

**Comment by pabloalonsogonzalez** [comment] 2017-11-07 16:36
Actually I believe that "flatmapCompletable" is totally necessary. In my case, I receive a flow from which I want to use data, but the flow that goes next must not emit any value.

```
private func addToken<T>(request : RequestBuilder<T>) -> Single<RequestBuilder<T>> {
        return Single.create {
            request.addHeaders([TokenRepository.headerKey : TokenRepository.sharedInstance.token!])
            $0(.success(request))
            return Disposables.create()
        }
    }

func secureRequest(request : RequestBuilder<Void>) -> Completable {
        return self.addToken(request: request)
            .flatMap {
                self.executeRequest(request: $0)
        }
    }

func executeRequest(request : RequestBuilder<Void>) -> Completable {
        return Completable.create(subscribe: { (observer) -> Disposable in
            request.execute({ (response, error) in
                    guard response != nil else {
                        let error = error ?? WebServiceError.unknown
                        observer(.error(error))
                        return
                    }
                    observer(.completed)
                })
            return Disposables.create()
        })
    }
```

**Comment by jordanebelanger** [comment] 2017-11-13 21:03
Here is an other use case I have for the same thing:

- Edit image on background thread -> (Single<UIImage>)
- Upload image to server -> Completable

The ability to do this is 100% necessary and makes total sense in a rx context. It feels real bad having to hack around rx to "simulate" this. Imo, the entire point of rx is to properly modelize these kinds of scenarios, if you have to hack around to do this, you might as well be using promise so that at least the intent of what you're doing is clear to other programmers reading your code.

**Comment by kzaher** [comment] 2017-11-20 14:45
It seems to me that there is a general feeling that using `Single` is preferred in all practical cases. My experience aligns with this, so let's close this for now.

**Closed by kzaher** 2017-11-20 14:45 UTC

**Comment by freak4pc** [comment] 2017-11-20 20:11
@kzaher Actually most responses here seem to indicate there are practical use cases to Completable ... I always fall back to not using Completable even in situation where it might fit, since there's no "easy" way to do `.asCompletable` from any trait

**Comment by kzaher** [comment] 2017-11-20 20:43
@freak4pc 

```
public func ignoreElements()
        -> Completable
```

**Comment by freak4pc** [comment] 2017-11-20 20:46
@kzaher That works but is poor for readability/discoverability I feel. What about aliasing `asCompletable` to this for non Observable<Never>s ? or do you feel that would be unneeded ?

**Comment by freak4pc** [comment] 2017-11-20 20:59
If you end up here, I ended up aliasing ignoreElements in my codebase for readability's sake. 

```swift
extension ObservableType {
    func asCompletable() -> Completable {
        return ignoreElements()
    }
}

extension PrimitiveSequence where Trait == SingleTrait {
    func asCompletable() -> Completable {
        return asObservable().ignoreElements()
    }
}

extension PrimitiveSequence where Trait == MaybeTrait {
    func asCompletable() -> Completable {
        return asObservable().ignoreElements()
    }
}
```

**Comment by kzaher** [comment] 2017-11-20 21:08
@freak4pc I think the only `discoverability` part might be non optimal. I think as far as readability is concerned, it does exactly what name suggests as far as I can tell.

If a sequence is a `Single` or `Maybe` that proves that it has 1 and 0-1 elements respectively. That means that some operator would need to be performed on it to ignore the elements to make it `Completable` (which means that sequence doesn't contain any element).

We've added `asSingle` because there isn't a way to prove compile time from type description of `Observable` sequence that it contains just one element, so we error out `Single` when it doesn't contain exactly one element.

In case of `Completable` we can prove compile time that `Observable` sequence doesn't contain any elements (typed `Never`). In case it can return elements, there is an operator that ignores all of the elements and returns `Completable`.

Like `RxJava`, `Completable` has `andThen` operator if chaining is wanted.

So far I haven't encountered any situation where using `Completable` is advantageous to `Single<()>`, so I wouldn't like to bloat the library with a lot of additional operators.

I think this should work at this moment.

```
func secureRequest(request : RequestBuilder<Void>) -> Completable {
        return self.addToken(request: request)
            .flatMap {
                self.executeRequest(request: $0).asObservable()
        }.asCompletable()
    }
```

If this was modeled as `Single`.

```
func secureRequest(request : RequestBuilder<Void>) -> Single<()> {
        return self.addToken(request: request)
            .flatMap {
                self.executeRequest(request: $0)
        }
    }
```

a bit cleaner.

**Comment by freak4pc** [comment] 2017-11-20 21:14
Thanks for your opinion :) 

The only point I'd like to "point on" is that Completable has a contextual meaning. 

Single means a Single element 
Maybe means a Single element or No Elements
and Completable means No Elements

Completable is the "Correct" Rx terminology declared by ReactiveX, and the fact we have Never in swift doesn't mean it needs to be hard to convert Observables to _any_ kind of trait (be it Single, Maybe or Completable). 

Using Single<Void> works _just as well_ but when I read a protocol that says "Completable", the mental load is much lower - I immediately understand contextually this means it would never return any values and can only fail or complete. 

Again, practically Single<Void> is the same, but contextually there is a slight difference.

Anyways I completely respect your will to keep the library slim which is why I added it as an extension on my own codebase. 

Thanks for the kind explanation, as usual :)

**Comment by pabloalonsogonzalez** [comment] 2017-11-21 15:35
I am totally agree with @freak4pc , I think that Single should emits a value. In fact, ReactiveX defined Completable for that purpose... 

In RxJava2, if a single emits no elements, an exception is thrown (NoSuchElementException)

**Comment by aufflick** [comment] 2017-12-07 00:08
The `ignoreElements()` comment from @kzaher seems right, except perhaps we don't want to change the existing api. I just hacked up the following extension using `ignoreElements()` and the existing `asCompletable()` that's already implemented for `Observable<Never>`

```
// allow turning anything into a Completable ignoring all events
public extension ObservableType {
    public func asCompletableIgnoringEvents() -> Completable {
        return self.ignoreElements()
            .map { _ in preconditionFailure() }
            .asCompletable()
    }
}
```

**Comment by aufflick** [comment] 2017-12-07 02:48
Also, I know this isn't really the place, but google leads people here, so wrt the question of `flatMap` on `Completable`, what you're really trying to do is wait for completion then start another signal. What I did for that is implemented the following `concat` extension on `Completable` so you can just `completable.concat(anyOtherTypeOfObservable)...`:

```
public extension PrimitiveSequence where Trait == CompletableTrait, Element == Swift.Never {
    
    public func concat<O>(_ second: O) -> RxSwift.Observable<O.E> where O : ObservableConvertibleType {
        return self.asObservable().map { _ -> O.E in preconditionFailure() }.concat(second)
    }
}
```

I should probably make this a patch for RxSwift or RxSwiftExtensions…

**Comment by kzaher** [comment] 2017-12-07 18:05
There is `andThen` operator for `Completable`.

**Comment by nikita-leonov** [comment] 2018-01-17 03:00
There is a difference for representing a `Single` or `Observable` as `Completable`by `ignoreElements`and making a single value or maybe value into `Completable`. You may have a function already that does take input and produce `Completable` and this function takes value of `Single` as input. There is no such a function yet besides proposed `flatMapCompletable`.

**Comment by tarunon** [comment] 2018-01-17 03:15
In my opinion, that make sense next `flatMap` overloading.

|Source＼Closure|`(T) -> Single<U>`|`(T) -> Maybe<U>`|`(T) -> Completable`|
|---|---|---|---|
|`Single<T>`|`Single<U>`|`Maybe<U>`|`Completable`|
|`Maybe<T>`|`Maybe<U>`|`Maybe<U>`|`Completable`|
※`Completable` has no `next`(success), so there is no implementation of `flatMap`

We often make the function that has 1 argument and return `Completable`, but if we wish to use this function in `PrimitiveSequence` chaining, I think there is no way to use this function.
`andThen` can connect from `Single` to `Completable`, but we cannot receive `next`(success) value.

How do you think? @kzaher

**Comment by hiragram** [comment] 2018-01-17 03:30
I absolutely agree with @tarunon.
I encounter that situation almost every day.

Currently I implement that architecture by this way,

```swift
func createComplexCompletable() -> Completable {
    return singleA
        .asObservable()
        .flatMap { valueA -> Observable<Never> in
            otherCreateCompletableMethod(arg: valueA) // <- returns Completable
                .asObservable()
        }
        .asCompletable()
}
```

Looks terrible. 🙃 

If I can write

```swift
func createComplexCompletable() -> Completable {
    return singleA
        .flatMap { valueA -> Completable in
            otherCreateCompletableMethod(arg: valueA)
        }
}
```

Looks smart. 😎

**Comment by HayTran94** [comment] 2018-12-08 04:35
> I absolutely agree with @tarunon.
> I encounter that situation almost every day.
> 
> Currently I implement that architecture by this way,
> 
> ```swift
> func createComplexCompletable() -> Completable {
>     return singleA
>         .asObservable()
>         .flatMap { valueA -> Observable<Never> in
>             otherCreateCompletableMethod(arg: valueA) // <- returns Completable
>                 .asObservable()
>         }
>         .asCompletable()
> }
> ```
> 
> Looks terrible. 🙃
> 
> If I can write
> 
> ```swift
> func createComplexCompletable() -> Completable {
>     return singleA
>         .flatMap { valueA -> Completable in
>             otherCreateCompletableMethod(arg: valueA)
>         }
> }
> ```
> 
> Looks smart. 😎

So don't we have any choice to implement this case @hiragram ?

**Comment by iandric** [comment] 2019-08-07 09:32
@HayTran94 Actually, we can write something slightly better:
```
func createComplexCompletable() -> Completable {
    return singleA
        .asObservable()
        .flatMap { valueA -> Completable in
            otherCreateCompletableMethod(arg: valueA) // <- returns Completable
        }
        .asCompletable()
}
```
Compiles fine on my machine.
