### ISSUE TITLE
shopsTableView.rx_itemSelected UI operations are executed with delay

### ISSUE THREAD

**Issue by croccio** [ReactiveX/RxSwift#124] opened 2015-09-02 16:03 UTC
shopsTableView.rx_itemSelected
            >- observeOn(doOnMainThread())
            >- subscribeNext { [unowned self] indexPath in
                
                let shop: PPTShop = self.filteredShops[indexPath.row]
                
                
                let cell: UITableViewCell = self.shopsTableView.cellForRowAtIndexPath(indexPath)!
                
                PPTUser.sharedInstance.selectedShop = shop
                PreferencesController.sharedInstance.saveSelectedShop(PPTUser.sharedInstance.selectedShop)
                sendNext(PPTUser.sharedInstance.rx_selectedShop, RxResult.Success(RxBox(PPTUser.sharedInstance.selectedShop)))
                
    //THIS IS CALLED WITH DELAY NOT ALWAYS, BUT SOMETIMES            
    self.navigationController?.dismissViewControllerAnimated(true, completion: nil)
            }

**Comment by croccio** [comment] 2015-09-02 16:14
if i do

    dispatch_async(dispatch_get_main_queue(),{
                    self.navigationController?.dismissViewControllerAnimated(true, completion: nil)
                    
                })


it not delay. is there anyway to delete dispatch_async?

**Comment by kzaher** [comment] 2015-09-02 20:33
Hi @croccio ,

I think I would need more information to answer this :)

When you do see that delay, could you paste a stack trace here?

In this particular case you don't need `>- observeOn(doOnMainThread())`

Maybe this helps? :)

**Comment by croccio** [comment] 2015-09-02 20:50
Thank you for answer. In log nothing of strange appear, where can i get a detailed stack trace? Because only UI action are dalayed, other thing no 

Inviato da iPhone

**Comment by kzaher** [comment] 2015-09-03 20:09
There is a `>- debug` operator. Maybe it can help you to figure out what's wrong.

It will print all events to console.

I'm not sure I can help you without any more information. It's hard for me to say from your description where is the problem :)

**Comment by croccio** [comment] 2015-09-03 20:50
Thank you. I'll try it. If the problem persist can i share my code with you? Maybe it'll can be only my code 

Inviato da iPhone

**Comment by kzaher** [comment] 2015-09-05 17:11
It would be great if you could try to debug it yourself first :)

I can try to take a peek at your code and see if you are using it in a wrong way, but it would be great if you could help us to point point the problem using `debug` operator traces, provide us with a trace, difference of that trace from expected behavior and a short code sample :)

**Comment by croccio** [comment] 2015-09-08 10:12
hi @kzaher i've post code sample in first post. do you need other? i try to remove all other line of code but the problem persist. i try to use debug operator, but i get this in log


[#####shopsTableView.rx_itemSelected####] subscribed
[#####shopsTableView.rx_itemSelected####] -> Event Next(Box(<NSIndexPat...= 2, path = 0 - 2}))

**Comment by kzaher** [comment] 2015-09-08 20:01
Hi @croccio ,

If you could create some small example that I can run to see that delay that would be great, if I can't reproduce the issue or understand what's happening, I'm not sure I can be of much help :)

You can also try to see what code is running while that delay is happening. I believe shortcut is Ctrl+Cmd+Y, so that could help you localize the issue. Rx is open sourced :)

**Comment by kzaher** [comment] 2015-10-04 11:12
Don't know what else to do with this, closing this for now. Don't know how to replicate this :)

**Closed by kzaher** 2015-10-04 11:12 UTC
Labels: question
