### ISSUE TITLE
protracted build time

### ISSUE THREAD

**Issue by ptrocki** [ReactiveX/RxSwift#1404] opened 2017-09-12 09:29 UTC
**Short description of the issue**:

Code no 1

```swift
Observable.combineLatest(emailTextField.rx.text, passwordTextField.rx.text, repeatPasswordTextField.rx.text, firstNameTextField.rx.text, lastNameTextField.rx.text) {
             (email, password, repeatPassword, firstName, lastname) -> Bool? in
            return email != ""  && password != "" && repeatPassword != "" && firstName != "" && lastname != ""
            }
```
Code no 2
```swift
Observable.combineLatest(emailTextField.rx.text, passwordTextField.rx.text, repeatPasswordTextField.rx.text, firstNameTextField.rx.text, lastNameTextField.rx.text)
            .map { (email, password, repeatPassword, firstName, lastname) -> Bool in
                return email.isNotEmpty()  && password.isNotEmpty() && repeatPassword.isNotEmpty() && firstName.isNotEmpty() && lastname.isNotEmpty() }
```

**Expected outcome**:

Should be the same time compilation but code no 1 builds almost 2 minutes, when code no 2 build about 10 seconds. 

**What actually happens**:

Code no 1 builds almost 2 minutes, when code no 2 build about 10 seconds. 

**Self contained code example that reproduces the issue**:

Above code 

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

Using RxSwift (3.6.1)

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.3.3 && 9 beta 6
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by ptrocki** [comment] 2017-09-12 09:31
I just want to know, what is cause of this problem. Because Idk if this is problem of Swift, XCode or Rx library.

**Comment by freak4pc** [comment] 2017-09-12 09:51
The problem is type inference. isEmpty is overloaded and applies to things that are not String so it might take more time for the compiler to understand. When you compare to "" it is explicit its a string. 

Adding types to your closure will solve this

```
.map { (email: String, password: String, repeatPassword: String, firstName: String, lastname: String) -> Bool in
```

Regardless, this is not an RxSwift problem, but a Swift issue, so I'll be closing this one :)

**Closed by freak4pc** 2017-09-12 09:51 UTC
